// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: medicalissues.proto

package ehr.medicalissues;

public final class Medicalissues {
  private Medicalissues() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * This will be a list of the most common medical issues. There are around 70,000
   * ICD-10 entries, and that's challenging to structure so v1 will be a minimalist
   * attempt.
   * </pre>
   *
   * Protobuf enum {@code ehr.medicalissues.MedicalIssue}
   */
  public enum MedicalIssue
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NO_MEDICAL_ISSUE = 0;</code>
     */
    NO_MEDICAL_ISSUE(0),
    /**
     * <code>ELEVATED_BLOOD_PRESSURE = 1;</code>
     */
    ELEVATED_BLOOD_PRESSURE(1),
    /**
     * <code>STAGE_ONE_HYPERTENSION = 2;</code>
     */
    STAGE_ONE_HYPERTENSION(2),
    /**
     * <code>STAGE_TWO_HYPERTENSION = 3;</code>
     */
    STAGE_TWO_HYPERTENSION(3),
    /**
     * <code>STAGE_THREE_HYPERTENSION = 4;</code>
     */
    STAGE_THREE_HYPERTENSION(4),
    /**
     * <code>HYPERTENSIVE_URGENCY = 5;</code>
     */
    HYPERTENSIVE_URGENCY(5),
    /**
     * <code>HYPERTENSIVE_EMERGENCY = 6;</code>
     */
    HYPERTENSIVE_EMERGENCY(6),
    /**
     * <code>ISCHEMIC_CORONARY_ARTERY_DISEASE = 7;</code>
     */
    ISCHEMIC_CORONARY_ARTERY_DISEASE(7),
    /**
     * <code>NONISCHEMIC_CORONARY_ARTERY_DISEASE = 8;</code>
     */
    NONISCHEMIC_CORONARY_ARTERY_DISEASE(8),
    /**
     * <code>SYSTOLIC_HEART_FAILURE = 9;</code>
     */
    SYSTOLIC_HEART_FAILURE(9),
    /**
     * <code>DIASTOLIC_HEART_FAILURE = 10;</code>
     */
    DIASTOLIC_HEART_FAILURE(10),
    /**
     * <code>ATRIAL_FIBRILLATION = 11;</code>
     */
    ATRIAL_FIBRILLATION(11),
    /**
     * <code>LONG_QT_SYNDROME = 12;</code>
     */
    LONG_QT_SYNDROME(12),
    /**
     * <code>VENTRICULAR_TACHYCARDIA = 13;</code>
     */
    VENTRICULAR_TACHYCARDIA(13),
    /**
     * <code>VENTRICULAR_FIBRILLATION = 14;</code>
     */
    VENTRICULAR_FIBRILLATION(14),
    /**
     * <code>WOLFE_PARKINSON_WHITE_SYNDROME = 15;</code>
     */
    WOLFE_PARKINSON_WHITE_SYNDROME(15),
    /**
     * <code>SUPRAVENTRICULAR_TACHYCARDIA = 16;</code>
     */
    SUPRAVENTRICULAR_TACHYCARDIA(16),
    /**
     * <code>OTHER_HEART_DYSRYTHMIA = 17;</code>
     */
    OTHER_HEART_DYSRYTHMIA(17),
    /**
     * <code>DEEP_VENOUS_THROMBOEMBOLISM = 18;</code>
     */
    DEEP_VENOUS_THROMBOEMBOLISM(18),
    /**
     * <code>SUPERFICIAL_VENOUS_THROMBOEMBOLISM = 19;</code>
     */
    SUPERFICIAL_VENOUS_THROMBOEMBOLISM(19),
    /**
     * <code>PULMONARY_EMBOLISM = 20;</code>
     */
    PULMONARY_EMBOLISM(20),
    /**
     * <code>SADDLE_EMBOLISM = 21;</code>
     */
    SADDLE_EMBOLISM(21),
    /**
     * <code>MITRAL_STENOSIS = 22;</code>
     */
    MITRAL_STENOSIS(22),
    /**
     * <code>MITRAL_REGURIGITATION = 23;</code>
     */
    MITRAL_REGURIGITATION(23),
    /**
     * <code>AORTIC_STENOSIS = 24;</code>
     */
    AORTIC_STENOSIS(24),
    /**
     * <code>AORTIC_REGURGITATION = 25;</code>
     */
    AORTIC_REGURGITATION(25),
    /**
     * <code>TRICUSPID_STENOSIS = 26;</code>
     */
    TRICUSPID_STENOSIS(26),
    /**
     * <code>TRICUSPID_REGURGITATION = 27;</code>
     */
    TRICUSPID_REGURGITATION(27),
    /**
     * <code>PERIPHERAL_VASCULAR_DISEASE = 28;</code>
     */
    PERIPHERAL_VASCULAR_DISEASE(28),
    /**
     * <code>CHRONIC_OBSTRUCTIVE_PULMONARY_DISEASE = 29;</code>
     */
    CHRONIC_OBSTRUCTIVE_PULMONARY_DISEASE(29),
    /**
     * <code>ASTHMA = 30;</code>
     */
    ASTHMA(30),
    /**
     * <code>SQUAMOUS_CELL_LUNG_CANCER = 31;</code>
     */
    SQUAMOUS_CELL_LUNG_CANCER(31),
    /**
     * <code>SMALL_CELL_LUNG_CANCER = 32;</code>
     */
    SMALL_CELL_LUNG_CANCER(32),
    /**
     * <code>ADENOCARCINOMA_LUNG_CANCER = 33;</code>
     */
    ADENOCARCINOMA_LUNG_CANCER(33),
    /**
     * <code>PNUEMONIA = 34;</code>
     */
    PNUEMONIA(34),
    /**
     * <code>PULMONARY_TUBERCULOSIS = 35;</code>
     */
    PULMONARY_TUBERCULOSIS(35),
    /**
     * <code>CYSTIC_FIBROSIS = 36;</code>
     */
    CYSTIC_FIBROSIS(36),
    /**
     * <code>DIFFUSE_INTERSTITIAL_LUNG_DISEASE = 37;</code>
     */
    DIFFUSE_INTERSTITIAL_LUNG_DISEASE(37),
    /**
     * <code>PNEUMOTHORAX = 38;</code>
     */
    PNEUMOTHORAX(38),
    /**
     * <code>TENSION_PNEUMOTHORAX = 39;</code>
     */
    TENSION_PNEUMOTHORAX(39),
    /**
     * <code>CEREBROVASCULAR_DISEASE = 40;</code>
     */
    CEREBROVASCULAR_DISEASE(40),
    /**
     * <code>HISTORY_OF_MYOCARDIAL_INFARCTION = 41;</code>
     */
    HISTORY_OF_MYOCARDIAL_INFARCTION(41),
    /**
     * <code>HISTORY_OF_CEREBROVASCULAR_INFARCTION = 42;</code>
     */
    HISTORY_OF_CEREBROVASCULAR_INFARCTION(42),
    /**
     * <code>EPILEPSY = 43;</code>
     */
    EPILEPSY(43),
    /**
     * <code>MENINGITIS = 44;</code>
     */
    MENINGITIS(44),
    /**
     * <code>HEAD_INJURY = 45;</code>
     */
    HEAD_INJURY(45),
    /**
     * <code>TRAUMATIC_BRAIN_INJRY = 46;</code>
     */
    TRAUMATIC_BRAIN_INJRY(46),
    /**
     * <code>TENSION_HEADACHE = 47;</code>
     */
    TENSION_HEADACHE(47),
    /**
     * <code>MIGRAINE_HEADACHE = 48;</code>
     */
    MIGRAINE_HEADACHE(48),
    /**
     * <code>CLUSTER_HEADACHE = 49;</code>
     */
    CLUSTER_HEADACHE(49),
    /**
     * <code>THUNDERCLAP_HEADACHE = 50;</code>
     */
    THUNDERCLAP_HEADACHE(50),
    /**
     * <code>SINUS_HEADACHE = 51;</code>
     */
    SINUS_HEADACHE(51),
    /**
     * <code>CAFFEINE_WITHDRAWAL_HEADACHE = 52;</code>
     */
    CAFFEINE_WITHDRAWAL_HEADACHE(52),
    /**
     * <code>EXERTION_HEADACHE = 53;</code>
     */
    EXERTION_HEADACHE(53),
    /**
     * <code>HYPERTENSION_HEADACHE = 54;</code>
     */
    HYPERTENSION_HEADACHE(54),
    /**
     * <code>POST_TRAUMATIC_HEADACHE = 55;</code>
     */
    POST_TRAUMATIC_HEADACHE(55),
    /**
     * <code>CHRONIC_TOE_PAIN = 56;</code>
     */
    CHRONIC_TOE_PAIN(56),
    /**
     * <code>CHRONIC_FOOT_PAIN = 57;</code>
     */
    CHRONIC_FOOT_PAIN(57),
    /**
     * <code>CHRONIC_ANKLE_PAIN = 58;</code>
     */
    CHRONIC_ANKLE_PAIN(58),
    /**
     * <code>CHRONIC_KNEE_PAIN = 59;</code>
     */
    CHRONIC_KNEE_PAIN(59),
    /**
     * <code>CHRONIC_HIP_PAIN = 60;</code>
     */
    CHRONIC_HIP_PAIN(60),
    /**
     * <code>CHRONIC_ABDOMINAL_PAIN = 61;</code>
     */
    CHRONIC_ABDOMINAL_PAIN(61),
    /**
     * <code>CHRONIC_LUMBAR_BACK_PAIN = 62;</code>
     */
    CHRONIC_LUMBAR_BACK_PAIN(62),
    /**
     * <code>CHRONIC_CHEST_PAIN = 63;</code>
     */
    CHRONIC_CHEST_PAIN(63),
    /**
     * <code>CHRONIC_THORACIC_BACK_PAIN = 64;</code>
     */
    CHRONIC_THORACIC_BACK_PAIN(64),
    /**
     * <code>CHRONIC_CERVICAL_SPINAL_PAIN = 65;</code>
     */
    CHRONIC_CERVICAL_SPINAL_PAIN(65),
    /**
     * <code>CHRONIC_SHOULDER_PAIN = 66;</code>
     */
    CHRONIC_SHOULDER_PAIN(66),
    /**
     * <code>CHRONIC_ELBOW_PAIN = 67;</code>
     */
    CHRONIC_ELBOW_PAIN(67),
    /**
     * <code>CHRONIC_WRIST_PAIN = 68;</code>
     */
    CHRONIC_WRIST_PAIN(68),
    /**
     * <code>CHRONIC_HAND_PAIN = 69;</code>
     */
    CHRONIC_HAND_PAIN(69),
    /**
     * <code>CHRONIC_FINGER_PAIN = 70;</code>
     */
    CHRONIC_FINGER_PAIN(70),
    /**
     * <code>ACUTE_TOE_PAIN = 71;</code>
     */
    ACUTE_TOE_PAIN(71),
    /**
     * <code>ACUTE_FOOT_PAIN = 72;</code>
     */
    ACUTE_FOOT_PAIN(72),
    /**
     * <code>ACUTE_ANKLE_PAIN = 73;</code>
     */
    ACUTE_ANKLE_PAIN(73),
    /**
     * <code>ACUTE_KNEE_PAIN = 74;</code>
     */
    ACUTE_KNEE_PAIN(74),
    /**
     * <code>ACUTE_HIP_PAIN = 75;</code>
     */
    ACUTE_HIP_PAIN(75),
    /**
     * <code>ACUTE_ABDOMINAL_PAIN = 76;</code>
     */
    ACUTE_ABDOMINAL_PAIN(76),
    /**
     * <code>ACUTE_LUMBAR_BACK_PAIN = 77;</code>
     */
    ACUTE_LUMBAR_BACK_PAIN(77),
    /**
     * <code>ACUTE_CHEST_PAIN = 78;</code>
     */
    ACUTE_CHEST_PAIN(78),
    /**
     * <code>ACUTE_THORACIC_BACK_PAIN = 79;</code>
     */
    ACUTE_THORACIC_BACK_PAIN(79),
    /**
     * <code>ACUTE_CERVICAL_SPINAL_PAIN = 80;</code>
     */
    ACUTE_CERVICAL_SPINAL_PAIN(80),
    /**
     * <code>ACUTE_SHOULDER_PAIN = 81;</code>
     */
    ACUTE_SHOULDER_PAIN(81),
    /**
     * <code>ACUTE_ELBOW_PAIN = 82;</code>
     */
    ACUTE_ELBOW_PAIN(82),
    /**
     * <code>ACUTE_WRIST_PAIN = 83;</code>
     */
    ACUTE_WRIST_PAIN(83),
    /**
     * <code>ACUTE_HAND_PAIN = 84;</code>
     */
    ACUTE_HAND_PAIN(84),
    /**
     * <code>ACUTE_FINGER_PAIN = 85;</code>
     */
    ACUTE_FINGER_PAIN(85),
    /**
     * <code>PARKINSONS_DISEASE = 86;</code>
     */
    PARKINSONS_DISEASE(86),
    /**
     * <code>ALZHEIMERS_DEMENTIA = 87;</code>
     */
    ALZHEIMERS_DEMENTIA(87),
    /**
     * <code>VASCULAR_DEMENTIA = 88;</code>
     */
    VASCULAR_DEMENTIA(88),
    /**
     * <code>LEWY_BODY_DEMENTIA = 89;</code>
     */
    LEWY_BODY_DEMENTIA(89),
    /**
     * <code>FRONTOTEMPORAL_DEMENTIA = 90;</code>
     */
    FRONTOTEMPORAL_DEMENTIA(90),
    /**
     * <code>HYPOACTIVE_DELIRIUM = 91;</code>
     */
    HYPOACTIVE_DELIRIUM(91),
    /**
     * <code>HYPERACTIVE_DELIRIUM = 92;</code>
     */
    HYPERACTIVE_DELIRIUM(92),
    /**
     * <code>MULTIPLE_SCLEROSIS = 93;</code>
     */
    MULTIPLE_SCLEROSIS(93),
    /**
     * <code>PROGRESSIVE_MUSCULAR_ATROPHY = 94;</code>
     */
    PROGRESSIVE_MUSCULAR_ATROPHY(94),
    /**
     * <code>AMYOTRPHIC_LATERAL_SCLEROSIS = 95;</code>
     */
    AMYOTRPHIC_LATERAL_SCLEROSIS(95),
    /**
     * <code>PROGRESSIVE_BULBAR_PALSY = 96;</code>
     */
    PROGRESSIVE_BULBAR_PALSY(96),
    /**
     * <code>PEPTIC_ULCER = 97;</code>
     */
    PEPTIC_ULCER(97),
    /**
     * <code>GASTRITIS = 98;</code>
     */
    GASTRITIS(98),
    /**
     * <code>GASTROESOPHAGEAL_REFLUX_DISEASE = 99;</code>
     */
    GASTROESOPHAGEAL_REFLUX_DISEASE(99),
    /**
     * <code>INFLAMMATORY_BOWEL_DISEASE = 100;</code>
     */
    INFLAMMATORY_BOWEL_DISEASE(100),
    /**
     * <code>ULCERATIVE_COLITIS = 101;</code>
     */
    ULCERATIVE_COLITIS(101),
    /**
     * <code>CHRONS_DISEASE = 102;</code>
     */
    CHRONS_DISEASE(102),
    /**
     * <code>HEPATITIS_A = 103;</code>
     */
    HEPATITIS_A(103),
    /**
     * <code>HEPATITIS_B = 104;</code>
     */
    HEPATITIS_B(104),
    /**
     * <code>HEPATITIS_C = 105;</code>
     */
    HEPATITIS_C(105),
    /**
     * <code>HEPATITIS_D = 106;</code>
     */
    HEPATITIS_D(106),
    /**
     * <code>COLORECTAL_CANCER = 107;</code>
     */
    COLORECTAL_CANCER(107),
    /**
     * <code>ESOPHAGEAL_CANCER = 108;</code>
     */
    ESOPHAGEAL_CANCER(108),
    /**
     * <code>GASTRIC_CANCER = 109;</code>
     */
    GASTRIC_CANCER(109),
    /**
     * <code>MALABSORPTION_SYNDROME = 110;</code>
     */
    MALABSORPTION_SYNDROME(110),
    /**
     * <code>DIABETES_MELLITUS_TYPE_2 = 111;</code>
     */
    DIABETES_MELLITUS_TYPE_2(111),
    /**
     * <code>DIABETES_MELLITIS_TYPE_1 = 112;</code>
     */
    DIABETES_MELLITIS_TYPE_1(112),
    /**
     * <code>ANOREXIA_NERVOSA = 113;</code>
     */
    ANOREXIA_NERVOSA(113),
    /**
     * <code>UNDERWEIGHT = 114;</code>
     */
    UNDERWEIGHT(114),
    /**
     * <code>NORMAL_WEIGHT = 115;</code>
     */
    NORMAL_WEIGHT(115),
    /**
     * <code>OVERWEIGHT = 116;</code>
     */
    OVERWEIGHT(116),
    /**
     * <code>OBESITY_CLASS_1 = 117;</code>
     */
    OBESITY_CLASS_1(117),
    /**
     * <code>OBESITY_CLASS_2 = 118;</code>
     */
    OBESITY_CLASS_2(118),
    /**
     * <code>OBESITY_CLASS_3 = 119;</code>
     */
    OBESITY_CLASS_3(119),
    /**
     * <code>METABOLIC_OBESITY_IN_NORMAL_WEIGHT = 120;</code>
     */
    METABOLIC_OBESITY_IN_NORMAL_WEIGHT(120),
    /**
     * <code>PROTEIN_ENERGY_MALNUTRITION = 121;</code>
     */
    PROTEIN_ENERGY_MALNUTRITION(121),
    /**
     * <code>HYPOTHYROIDISM_UNSPECIFIED = 122;</code>
     */
    HYPOTHYROIDISM_UNSPECIFIED(122),
    /**
     * <code>HYPERTHYROIDISM_UNSPECIFIED = 123;</code>
     */
    HYPERTHYROIDISM_UNSPECIFIED(123),
    /**
     * <code>THYROIDITIS = 124;</code>
     */
    THYROIDITIS(124),
    /**
     * <code>THYROID_CANCER = 125;</code>
     */
    THYROID_CANCER(125),
    /**
     * <code>PARATHYROID_CANCER = 126;</code>
     */
    PARATHYROID_CANCER(126),
    /**
     * <code>HYPERPARATHYROID_SYNDROME = 127;</code>
     */
    HYPERPARATHYROID_SYNDROME(127),
    /**
     * <code>OSTEOARTHRITIS = 128;</code>
     */
    OSTEOARTHRITIS(128),
    /**
     * <code>RHEUMATOID_ARTHRITIS = 129;</code>
     */
    RHEUMATOID_ARTHRITIS(129),
    /**
     * <code>OSTEOPENIA = 130;</code>
     */
    OSTEOPENIA(130),
    /**
     * <code>OSTEOPOROSIS = 131;</code>
     */
    OSTEOPOROSIS(131),
    /**
     * <code>SEPTIC_ARTHRITIS = 132;</code>
     */
    SEPTIC_ARTHRITIS(132),
    /**
     * <code>GOUT = 133;</code>
     */
    GOUT(133),
    /**
     * <code>PSEUDO_GOUT = 134;</code>
     */
    PSEUDO_GOUT(134),
    /**
     * <code>MYASTHENIA_GRAVIS = 135;</code>
     */
    MYASTHENIA_GRAVIS(135),
    /**
     * <code>SYSTEMIC_LUPUS_ERYTHEMATOSUS = 136;</code>
     */
    SYSTEMIC_LUPUS_ERYTHEMATOSUS(136),
    /**
     * <code>URINARY_TRACT_INFECTION = 137;</code>
     */
    URINARY_TRACT_INFECTION(137),
    /**
     * <code>PYELONEPHRITIS = 138;</code>
     */
    PYELONEPHRITIS(138),
    /**
     * <code>BENIGN_PROSTATE_HYPERTROPHY = 139;</code>
     */
    BENIGN_PROSTATE_HYPERTROPHY(139),
    /**
     * <code>PROSTATE_CANCER = 140;</code>
     */
    PROSTATE_CANCER(140),
    /**
     * <code>RENAL_CALCULI = 141;</code>
     */
    RENAL_CALCULI(141),
    /**
     * <code>RENAL_FAILURE_STAGE_1 = 142;</code>
     */
    RENAL_FAILURE_STAGE_1(142),
    /**
     * <code>RENAL_FAILURE_STAGE_2 = 143;</code>
     */
    RENAL_FAILURE_STAGE_2(143),
    /**
     * <code>RENAL_FAILURE_STAGE_3A = 144;</code>
     */
    RENAL_FAILURE_STAGE_3A(144),
    /**
     * <code>RENAL_FAILURE_STAGE_3B = 145;</code>
     */
    RENAL_FAILURE_STAGE_3B(145),
    /**
     * <code>RENAL_FAILURE_STAGE_4 = 146;</code>
     */
    RENAL_FAILURE_STAGE_4(146),
    /**
     * <code>RENAL_FAILURE_STAGE_5 = 147;</code>
     */
    RENAL_FAILURE_STAGE_5(147),
    /**
     * <code>HEMODIALYSIS = 148;</code>
     */
    HEMODIALYSIS(148),
    /**
     * <code>PERITONEAL_DIALYSIS = 149;</code>
     */
    PERITONEAL_DIALYSIS(149),
    /**
     * <code>PREGNANCY = 150;</code>
     */
    PREGNANCY(150),
    /**
     * <code>SPONTANEOUS_ABORTION = 151;</code>
     */
    SPONTANEOUS_ABORTION(151),
    /**
     * <code>THERAPEUTIC_ABORATION = 152;</code>
     */
    THERAPEUTIC_ABORATION(152),
    /**
     * <code>INFERTILITY = 153;</code>
     */
    INFERTILITY(153),
    /**
     * <code>CONTRACEPTIVE_USE = 154;</code>
     */
    CONTRACEPTIVE_USE(154),
    /**
     * <code>OLIGOMENORRHEA = 155;</code>
     */
    OLIGOMENORRHEA(155),
    /**
     * <code>DYSMENORRHEA = 156;</code>
     */
    DYSMENORRHEA(156),
    /**
     * <code>PRIMARY_AMENORRHEA = 157;</code>
     */
    PRIMARY_AMENORRHEA(157),
    /**
     * <code>SECONDARY_AMENORRHEA = 158;</code>
     */
    SECONDARY_AMENORRHEA(158),
    /**
     * <code>ENDOMETRIOSIS = 159;</code>
     */
    ENDOMETRIOSIS(159),
    /**
     * <code>SURGICAL_MENOPAUSE = 160;</code>
     */
    SURGICAL_MENOPAUSE(160),
    /**
     * <code>EARLY_MENOPAUSE = 161;</code>
     */
    EARLY_MENOPAUSE(161),
    /**
     * <code>PERIMENOPAUSE = 162;</code>
     */
    PERIMENOPAUSE(162),
    /**
     * <code>POST_MENOPAUSE = 163;</code>
     */
    POST_MENOPAUSE(163),
    /**
     * <code>POST_MENOPAUSAL_BLEED = 164;</code>
     */
    POST_MENOPAUSAL_BLEED(164),
    /**
     * <code>BREAST_CANCER = 165;</code>
     */
    BREAST_CANCER(165),
    /**
     * <code>CERVICAL_CANCER = 166;</code>
     */
    CERVICAL_CANCER(166),
    /**
     * <code>OVARIAN_CANCER = 167;</code>
     */
    OVARIAN_CANCER(167),
    /**
     * <code>ERECTILE_DYSFUNCTION = 168;</code>
     */
    ERECTILE_DYSFUNCTION(168),
    /**
     * <code>TESTICULAR_CANCER = 169;</code>
     */
    TESTICULAR_CANCER(169),
    /**
     * <code>TESTICULAR_TORSION = 170;</code>
     */
    TESTICULAR_TORSION(170),
    /**
     * <code>TESTICULAR_PAIN = 171;</code>
     */
    TESTICULAR_PAIN(171),
    /**
     * <code>VAGINAL_PAIN = 172;</code>
     */
    VAGINAL_PAIN(172),
    /**
     * <code>ANAL_PAIN = 173;</code>
     */
    ANAL_PAIN(173),
    /**
     * <code>ANEMIA_UNSPECIFIED = 174;</code>
     */
    ANEMIA_UNSPECIFIED(174),
    /**
     * <code>IRON_DEFICIENCY_ANEMIA = 175;</code>
     */
    IRON_DEFICIENCY_ANEMIA(175),
    /**
     * <code>SICKLE_CELL_DISEASE = 176;</code>
     */
    SICKLE_CELL_DISEASE(176),
    /**
     * <code>MACROCYTIC_ANEMIA = 177;</code>
     */
    MACROCYTIC_ANEMIA(177),
    /**
     * <code>MICROCYTIC_ANEMIA = 178;</code>
     */
    MICROCYTIC_ANEMIA(178),
    /**
     * <code>LEUKEMIA = 179;</code>
     */
    LEUKEMIA(179),
    /**
     * <code>LYMPHOMA = 180;</code>
     */
    LYMPHOMA(180),
    /**
     * <code>MYELOMA = 181;</code>
     */
    MYELOMA(181),
    /**
     * <code>HEMOPHILIA_A = 182;</code>
     */
    HEMOPHILIA_A(182),
    /**
     * <code>DEPRESSION = 183;</code>
     */
    DEPRESSION(183),
    /**
     * <code>SCHIZOPHRENIA = 184;</code>
     */
    SCHIZOPHRENIA(184),
    /**
     * <code>BIPOLAR_DISORDER = 185;</code>
     */
    BIPOLAR_DISORDER(185),
    /**
     * <code>ANXIETY_DISORDER = 186;</code>
     */
    ANXIETY_DISORDER(186),
    /**
     * <code>ADDICTION = 187;</code>
     */
    ADDICTION(187),
    /**
     * <code>EATING_DISORDER = 188;</code>
     */
    EATING_DISORDER(188),
    /**
     * <code>PREMATURE_BIRTH = 189;</code>
     */
    PREMATURE_BIRTH(189),
    /**
     * <code>BRONCHIOLITIS = 190;</code>
     */
    BRONCHIOLITIS(190),
    /**
     * <code>CROUP = 191;</code>
     */
    CROUP(191),
    /**
     * <code>CEREBRAL_PALSY = 192;</code>
     */
    CEREBRAL_PALSY(192),
    /**
     * <code>FAILURE_TO_THRIVE = 193;</code>
     */
    FAILURE_TO_THRIVE(193),
    /**
     * <code>CHILD_ABUSE = 194;</code>
     */
    CHILD_ABUSE(194),
    /**
     * <code>ELDER_ABUSE = 195;</code>
     */
    ELDER_ABUSE(195),
    /**
     * <code>HUMAN_IMMUNIDEFICIENCY_VIRUS_INFECTION = 196;</code>
     */
    HUMAN_IMMUNIDEFICIENCY_VIRUS_INFECTION(196),
    /**
     * <code>ACQUIRED_IMMUNE_DEFICIENCY_SYNDROME = 197;</code>
     */
    ACQUIRED_IMMUNE_DEFICIENCY_SYNDROME(197),
    /**
     * <code>MALARIA = 198;</code>
     */
    MALARIA(198),
    /**
     * <code>CHOLERA = 199;</code>
     */
    CHOLERA(199),
    /**
     * <code>IMMUNIZATION = 200;</code>
     */
    IMMUNIZATION(200),
    /**
     * <code>ECZEMA = 201;</code>
     */
    ECZEMA(201),
    /**
     * <code>DERMATITIS_UNSPECIFIED = 202;</code>
     */
    DERMATITIS_UNSPECIFIED(202),
    /**
     * <code>PSORIASIS = 203;</code>
     */
    PSORIASIS(203),
    /**
     * <code>PEMPHIGUS = 204;</code>
     */
    PEMPHIGUS(204),
    /**
     * <code>PEMPHIGOID = 205;</code>
     */
    PEMPHIGOID(205),
    /**
     * <code>ERYTHEMA_MULTIFORME = 206;</code>
     */
    ERYTHEMA_MULTIFORME(206),
    /**
     * <code>ERYTHEMA_NODOSUM = 207;</code>
     */
    ERYTHEMA_NODOSUM(207),
    /**
     * <code>SQUAMOUS_CELL_SKIN_CANCER = 208;</code>
     */
    SQUAMOUS_CELL_SKIN_CANCER(208),
    /**
     * <code>BASASL_CELL_SKIN_CANCER = 209;</code>
     */
    BASASL_CELL_SKIN_CANCER(209),
    /**
     * <code>MELANOMA_SKIN_CANCER = 210;</code>
     */
    MELANOMA_SKIN_CANCER(210),
    /**
     * <code>ACUTE_ABDOMEN = 211;</code>
     */
    ACUTE_ABDOMEN(211),
    /**
     * <code>APPENDICITIS = 212;</code>
     */
    APPENDICITIS(212),
    /**
     * <code>DIVERTICULITIS = 213;</code>
     */
    DIVERTICULITIS(213),
    /**
     * <code>DIVERTICULOSIS = 214;</code>
     */
    DIVERTICULOSIS(214),
    /**
     * <code>CHRONIC_PANCREATITIS = 215;</code>
     */
    CHRONIC_PANCREATITIS(215),
    /**
     * <code>ACUTE_PANCREATITIS = 216;</code>
     */
    ACUTE_PANCREATITIS(216),
    /**
     * <code>ALCOHOLIC_PANCREATITIS = 217;</code>
     */
    ALCOHOLIC_PANCREATITIS(217),
    /**
     * <code>GALL_STONE_PANCREATITIS = 218;</code>
     */
    GALL_STONE_PANCREATITIS(218),
    /**
     * <code>SMALL_BOWEL_OBSTRUCTION = 219;</code>
     */
    SMALL_BOWEL_OBSTRUCTION(219),
    /**
     * <code>LARGE_BOWEL_OBSTRUCTION = 220;</code>
     */
    LARGE_BOWEL_OBSTRUCTION(220),
    /**
     * <code>INGUINAL_HERNIA = 221;</code>
     */
    INGUINAL_HERNIA(221),
    /**
     * <code>PERIUMBILICAL_HERNIA = 222;</code>
     */
    PERIUMBILICAL_HERNIA(222),
    /**
     * <code>VENTRAL_HERNIA = 223;</code>
     */
    VENTRAL_HERNIA(223),
    /**
     * <code>INTERNAL_HEMORRHOIDS = 224;</code>
     */
    INTERNAL_HEMORRHOIDS(224),
    /**
     * <code>EXTERNAL_HEMORRHOIDS = 225;</code>
     */
    EXTERNAL_HEMORRHOIDS(225),
    /**
     * <code>ANAL_FISSURE = 226;</code>
     */
    ANAL_FISSURE(226),
    /**
     * <code>GRAVES_DISEASE = 227;</code>
     */
    GRAVES_DISEASE(227),
    /**
     * <code>CHOLECYSTITS = 228;</code>
     */
    CHOLECYSTITS(228),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NO_MEDICAL_ISSUE = 0;</code>
     */
    public static final int NO_MEDICAL_ISSUE_VALUE = 0;
    /**
     * <code>ELEVATED_BLOOD_PRESSURE = 1;</code>
     */
    public static final int ELEVATED_BLOOD_PRESSURE_VALUE = 1;
    /**
     * <code>STAGE_ONE_HYPERTENSION = 2;</code>
     */
    public static final int STAGE_ONE_HYPERTENSION_VALUE = 2;
    /**
     * <code>STAGE_TWO_HYPERTENSION = 3;</code>
     */
    public static final int STAGE_TWO_HYPERTENSION_VALUE = 3;
    /**
     * <code>STAGE_THREE_HYPERTENSION = 4;</code>
     */
    public static final int STAGE_THREE_HYPERTENSION_VALUE = 4;
    /**
     * <code>HYPERTENSIVE_URGENCY = 5;</code>
     */
    public static final int HYPERTENSIVE_URGENCY_VALUE = 5;
    /**
     * <code>HYPERTENSIVE_EMERGENCY = 6;</code>
     */
    public static final int HYPERTENSIVE_EMERGENCY_VALUE = 6;
    /**
     * <code>ISCHEMIC_CORONARY_ARTERY_DISEASE = 7;</code>
     */
    public static final int ISCHEMIC_CORONARY_ARTERY_DISEASE_VALUE = 7;
    /**
     * <code>NONISCHEMIC_CORONARY_ARTERY_DISEASE = 8;</code>
     */
    public static final int NONISCHEMIC_CORONARY_ARTERY_DISEASE_VALUE = 8;
    /**
     * <code>SYSTOLIC_HEART_FAILURE = 9;</code>
     */
    public static final int SYSTOLIC_HEART_FAILURE_VALUE = 9;
    /**
     * <code>DIASTOLIC_HEART_FAILURE = 10;</code>
     */
    public static final int DIASTOLIC_HEART_FAILURE_VALUE = 10;
    /**
     * <code>ATRIAL_FIBRILLATION = 11;</code>
     */
    public static final int ATRIAL_FIBRILLATION_VALUE = 11;
    /**
     * <code>LONG_QT_SYNDROME = 12;</code>
     */
    public static final int LONG_QT_SYNDROME_VALUE = 12;
    /**
     * <code>VENTRICULAR_TACHYCARDIA = 13;</code>
     */
    public static final int VENTRICULAR_TACHYCARDIA_VALUE = 13;
    /**
     * <code>VENTRICULAR_FIBRILLATION = 14;</code>
     */
    public static final int VENTRICULAR_FIBRILLATION_VALUE = 14;
    /**
     * <code>WOLFE_PARKINSON_WHITE_SYNDROME = 15;</code>
     */
    public static final int WOLFE_PARKINSON_WHITE_SYNDROME_VALUE = 15;
    /**
     * <code>SUPRAVENTRICULAR_TACHYCARDIA = 16;</code>
     */
    public static final int SUPRAVENTRICULAR_TACHYCARDIA_VALUE = 16;
    /**
     * <code>OTHER_HEART_DYSRYTHMIA = 17;</code>
     */
    public static final int OTHER_HEART_DYSRYTHMIA_VALUE = 17;
    /**
     * <code>DEEP_VENOUS_THROMBOEMBOLISM = 18;</code>
     */
    public static final int DEEP_VENOUS_THROMBOEMBOLISM_VALUE = 18;
    /**
     * <code>SUPERFICIAL_VENOUS_THROMBOEMBOLISM = 19;</code>
     */
    public static final int SUPERFICIAL_VENOUS_THROMBOEMBOLISM_VALUE = 19;
    /**
     * <code>PULMONARY_EMBOLISM = 20;</code>
     */
    public static final int PULMONARY_EMBOLISM_VALUE = 20;
    /**
     * <code>SADDLE_EMBOLISM = 21;</code>
     */
    public static final int SADDLE_EMBOLISM_VALUE = 21;
    /**
     * <code>MITRAL_STENOSIS = 22;</code>
     */
    public static final int MITRAL_STENOSIS_VALUE = 22;
    /**
     * <code>MITRAL_REGURIGITATION = 23;</code>
     */
    public static final int MITRAL_REGURIGITATION_VALUE = 23;
    /**
     * <code>AORTIC_STENOSIS = 24;</code>
     */
    public static final int AORTIC_STENOSIS_VALUE = 24;
    /**
     * <code>AORTIC_REGURGITATION = 25;</code>
     */
    public static final int AORTIC_REGURGITATION_VALUE = 25;
    /**
     * <code>TRICUSPID_STENOSIS = 26;</code>
     */
    public static final int TRICUSPID_STENOSIS_VALUE = 26;
    /**
     * <code>TRICUSPID_REGURGITATION = 27;</code>
     */
    public static final int TRICUSPID_REGURGITATION_VALUE = 27;
    /**
     * <code>PERIPHERAL_VASCULAR_DISEASE = 28;</code>
     */
    public static final int PERIPHERAL_VASCULAR_DISEASE_VALUE = 28;
    /**
     * <code>CHRONIC_OBSTRUCTIVE_PULMONARY_DISEASE = 29;</code>
     */
    public static final int CHRONIC_OBSTRUCTIVE_PULMONARY_DISEASE_VALUE = 29;
    /**
     * <code>ASTHMA = 30;</code>
     */
    public static final int ASTHMA_VALUE = 30;
    /**
     * <code>SQUAMOUS_CELL_LUNG_CANCER = 31;</code>
     */
    public static final int SQUAMOUS_CELL_LUNG_CANCER_VALUE = 31;
    /**
     * <code>SMALL_CELL_LUNG_CANCER = 32;</code>
     */
    public static final int SMALL_CELL_LUNG_CANCER_VALUE = 32;
    /**
     * <code>ADENOCARCINOMA_LUNG_CANCER = 33;</code>
     */
    public static final int ADENOCARCINOMA_LUNG_CANCER_VALUE = 33;
    /**
     * <code>PNUEMONIA = 34;</code>
     */
    public static final int PNUEMONIA_VALUE = 34;
    /**
     * <code>PULMONARY_TUBERCULOSIS = 35;</code>
     */
    public static final int PULMONARY_TUBERCULOSIS_VALUE = 35;
    /**
     * <code>CYSTIC_FIBROSIS = 36;</code>
     */
    public static final int CYSTIC_FIBROSIS_VALUE = 36;
    /**
     * <code>DIFFUSE_INTERSTITIAL_LUNG_DISEASE = 37;</code>
     */
    public static final int DIFFUSE_INTERSTITIAL_LUNG_DISEASE_VALUE = 37;
    /**
     * <code>PNEUMOTHORAX = 38;</code>
     */
    public static final int PNEUMOTHORAX_VALUE = 38;
    /**
     * <code>TENSION_PNEUMOTHORAX = 39;</code>
     */
    public static final int TENSION_PNEUMOTHORAX_VALUE = 39;
    /**
     * <code>CEREBROVASCULAR_DISEASE = 40;</code>
     */
    public static final int CEREBROVASCULAR_DISEASE_VALUE = 40;
    /**
     * <code>HISTORY_OF_MYOCARDIAL_INFARCTION = 41;</code>
     */
    public static final int HISTORY_OF_MYOCARDIAL_INFARCTION_VALUE = 41;
    /**
     * <code>HISTORY_OF_CEREBROVASCULAR_INFARCTION = 42;</code>
     */
    public static final int HISTORY_OF_CEREBROVASCULAR_INFARCTION_VALUE = 42;
    /**
     * <code>EPILEPSY = 43;</code>
     */
    public static final int EPILEPSY_VALUE = 43;
    /**
     * <code>MENINGITIS = 44;</code>
     */
    public static final int MENINGITIS_VALUE = 44;
    /**
     * <code>HEAD_INJURY = 45;</code>
     */
    public static final int HEAD_INJURY_VALUE = 45;
    /**
     * <code>TRAUMATIC_BRAIN_INJRY = 46;</code>
     */
    public static final int TRAUMATIC_BRAIN_INJRY_VALUE = 46;
    /**
     * <code>TENSION_HEADACHE = 47;</code>
     */
    public static final int TENSION_HEADACHE_VALUE = 47;
    /**
     * <code>MIGRAINE_HEADACHE = 48;</code>
     */
    public static final int MIGRAINE_HEADACHE_VALUE = 48;
    /**
     * <code>CLUSTER_HEADACHE = 49;</code>
     */
    public static final int CLUSTER_HEADACHE_VALUE = 49;
    /**
     * <code>THUNDERCLAP_HEADACHE = 50;</code>
     */
    public static final int THUNDERCLAP_HEADACHE_VALUE = 50;
    /**
     * <code>SINUS_HEADACHE = 51;</code>
     */
    public static final int SINUS_HEADACHE_VALUE = 51;
    /**
     * <code>CAFFEINE_WITHDRAWAL_HEADACHE = 52;</code>
     */
    public static final int CAFFEINE_WITHDRAWAL_HEADACHE_VALUE = 52;
    /**
     * <code>EXERTION_HEADACHE = 53;</code>
     */
    public static final int EXERTION_HEADACHE_VALUE = 53;
    /**
     * <code>HYPERTENSION_HEADACHE = 54;</code>
     */
    public static final int HYPERTENSION_HEADACHE_VALUE = 54;
    /**
     * <code>POST_TRAUMATIC_HEADACHE = 55;</code>
     */
    public static final int POST_TRAUMATIC_HEADACHE_VALUE = 55;
    /**
     * <code>CHRONIC_TOE_PAIN = 56;</code>
     */
    public static final int CHRONIC_TOE_PAIN_VALUE = 56;
    /**
     * <code>CHRONIC_FOOT_PAIN = 57;</code>
     */
    public static final int CHRONIC_FOOT_PAIN_VALUE = 57;
    /**
     * <code>CHRONIC_ANKLE_PAIN = 58;</code>
     */
    public static final int CHRONIC_ANKLE_PAIN_VALUE = 58;
    /**
     * <code>CHRONIC_KNEE_PAIN = 59;</code>
     */
    public static final int CHRONIC_KNEE_PAIN_VALUE = 59;
    /**
     * <code>CHRONIC_HIP_PAIN = 60;</code>
     */
    public static final int CHRONIC_HIP_PAIN_VALUE = 60;
    /**
     * <code>CHRONIC_ABDOMINAL_PAIN = 61;</code>
     */
    public static final int CHRONIC_ABDOMINAL_PAIN_VALUE = 61;
    /**
     * <code>CHRONIC_LUMBAR_BACK_PAIN = 62;</code>
     */
    public static final int CHRONIC_LUMBAR_BACK_PAIN_VALUE = 62;
    /**
     * <code>CHRONIC_CHEST_PAIN = 63;</code>
     */
    public static final int CHRONIC_CHEST_PAIN_VALUE = 63;
    /**
     * <code>CHRONIC_THORACIC_BACK_PAIN = 64;</code>
     */
    public static final int CHRONIC_THORACIC_BACK_PAIN_VALUE = 64;
    /**
     * <code>CHRONIC_CERVICAL_SPINAL_PAIN = 65;</code>
     */
    public static final int CHRONIC_CERVICAL_SPINAL_PAIN_VALUE = 65;
    /**
     * <code>CHRONIC_SHOULDER_PAIN = 66;</code>
     */
    public static final int CHRONIC_SHOULDER_PAIN_VALUE = 66;
    /**
     * <code>CHRONIC_ELBOW_PAIN = 67;</code>
     */
    public static final int CHRONIC_ELBOW_PAIN_VALUE = 67;
    /**
     * <code>CHRONIC_WRIST_PAIN = 68;</code>
     */
    public static final int CHRONIC_WRIST_PAIN_VALUE = 68;
    /**
     * <code>CHRONIC_HAND_PAIN = 69;</code>
     */
    public static final int CHRONIC_HAND_PAIN_VALUE = 69;
    /**
     * <code>CHRONIC_FINGER_PAIN = 70;</code>
     */
    public static final int CHRONIC_FINGER_PAIN_VALUE = 70;
    /**
     * <code>ACUTE_TOE_PAIN = 71;</code>
     */
    public static final int ACUTE_TOE_PAIN_VALUE = 71;
    /**
     * <code>ACUTE_FOOT_PAIN = 72;</code>
     */
    public static final int ACUTE_FOOT_PAIN_VALUE = 72;
    /**
     * <code>ACUTE_ANKLE_PAIN = 73;</code>
     */
    public static final int ACUTE_ANKLE_PAIN_VALUE = 73;
    /**
     * <code>ACUTE_KNEE_PAIN = 74;</code>
     */
    public static final int ACUTE_KNEE_PAIN_VALUE = 74;
    /**
     * <code>ACUTE_HIP_PAIN = 75;</code>
     */
    public static final int ACUTE_HIP_PAIN_VALUE = 75;
    /**
     * <code>ACUTE_ABDOMINAL_PAIN = 76;</code>
     */
    public static final int ACUTE_ABDOMINAL_PAIN_VALUE = 76;
    /**
     * <code>ACUTE_LUMBAR_BACK_PAIN = 77;</code>
     */
    public static final int ACUTE_LUMBAR_BACK_PAIN_VALUE = 77;
    /**
     * <code>ACUTE_CHEST_PAIN = 78;</code>
     */
    public static final int ACUTE_CHEST_PAIN_VALUE = 78;
    /**
     * <code>ACUTE_THORACIC_BACK_PAIN = 79;</code>
     */
    public static final int ACUTE_THORACIC_BACK_PAIN_VALUE = 79;
    /**
     * <code>ACUTE_CERVICAL_SPINAL_PAIN = 80;</code>
     */
    public static final int ACUTE_CERVICAL_SPINAL_PAIN_VALUE = 80;
    /**
     * <code>ACUTE_SHOULDER_PAIN = 81;</code>
     */
    public static final int ACUTE_SHOULDER_PAIN_VALUE = 81;
    /**
     * <code>ACUTE_ELBOW_PAIN = 82;</code>
     */
    public static final int ACUTE_ELBOW_PAIN_VALUE = 82;
    /**
     * <code>ACUTE_WRIST_PAIN = 83;</code>
     */
    public static final int ACUTE_WRIST_PAIN_VALUE = 83;
    /**
     * <code>ACUTE_HAND_PAIN = 84;</code>
     */
    public static final int ACUTE_HAND_PAIN_VALUE = 84;
    /**
     * <code>ACUTE_FINGER_PAIN = 85;</code>
     */
    public static final int ACUTE_FINGER_PAIN_VALUE = 85;
    /**
     * <code>PARKINSONS_DISEASE = 86;</code>
     */
    public static final int PARKINSONS_DISEASE_VALUE = 86;
    /**
     * <code>ALZHEIMERS_DEMENTIA = 87;</code>
     */
    public static final int ALZHEIMERS_DEMENTIA_VALUE = 87;
    /**
     * <code>VASCULAR_DEMENTIA = 88;</code>
     */
    public static final int VASCULAR_DEMENTIA_VALUE = 88;
    /**
     * <code>LEWY_BODY_DEMENTIA = 89;</code>
     */
    public static final int LEWY_BODY_DEMENTIA_VALUE = 89;
    /**
     * <code>FRONTOTEMPORAL_DEMENTIA = 90;</code>
     */
    public static final int FRONTOTEMPORAL_DEMENTIA_VALUE = 90;
    /**
     * <code>HYPOACTIVE_DELIRIUM = 91;</code>
     */
    public static final int HYPOACTIVE_DELIRIUM_VALUE = 91;
    /**
     * <code>HYPERACTIVE_DELIRIUM = 92;</code>
     */
    public static final int HYPERACTIVE_DELIRIUM_VALUE = 92;
    /**
     * <code>MULTIPLE_SCLEROSIS = 93;</code>
     */
    public static final int MULTIPLE_SCLEROSIS_VALUE = 93;
    /**
     * <code>PROGRESSIVE_MUSCULAR_ATROPHY = 94;</code>
     */
    public static final int PROGRESSIVE_MUSCULAR_ATROPHY_VALUE = 94;
    /**
     * <code>AMYOTRPHIC_LATERAL_SCLEROSIS = 95;</code>
     */
    public static final int AMYOTRPHIC_LATERAL_SCLEROSIS_VALUE = 95;
    /**
     * <code>PROGRESSIVE_BULBAR_PALSY = 96;</code>
     */
    public static final int PROGRESSIVE_BULBAR_PALSY_VALUE = 96;
    /**
     * <code>PEPTIC_ULCER = 97;</code>
     */
    public static final int PEPTIC_ULCER_VALUE = 97;
    /**
     * <code>GASTRITIS = 98;</code>
     */
    public static final int GASTRITIS_VALUE = 98;
    /**
     * <code>GASTROESOPHAGEAL_REFLUX_DISEASE = 99;</code>
     */
    public static final int GASTROESOPHAGEAL_REFLUX_DISEASE_VALUE = 99;
    /**
     * <code>INFLAMMATORY_BOWEL_DISEASE = 100;</code>
     */
    public static final int INFLAMMATORY_BOWEL_DISEASE_VALUE = 100;
    /**
     * <code>ULCERATIVE_COLITIS = 101;</code>
     */
    public static final int ULCERATIVE_COLITIS_VALUE = 101;
    /**
     * <code>CHRONS_DISEASE = 102;</code>
     */
    public static final int CHRONS_DISEASE_VALUE = 102;
    /**
     * <code>HEPATITIS_A = 103;</code>
     */
    public static final int HEPATITIS_A_VALUE = 103;
    /**
     * <code>HEPATITIS_B = 104;</code>
     */
    public static final int HEPATITIS_B_VALUE = 104;
    /**
     * <code>HEPATITIS_C = 105;</code>
     */
    public static final int HEPATITIS_C_VALUE = 105;
    /**
     * <code>HEPATITIS_D = 106;</code>
     */
    public static final int HEPATITIS_D_VALUE = 106;
    /**
     * <code>COLORECTAL_CANCER = 107;</code>
     */
    public static final int COLORECTAL_CANCER_VALUE = 107;
    /**
     * <code>ESOPHAGEAL_CANCER = 108;</code>
     */
    public static final int ESOPHAGEAL_CANCER_VALUE = 108;
    /**
     * <code>GASTRIC_CANCER = 109;</code>
     */
    public static final int GASTRIC_CANCER_VALUE = 109;
    /**
     * <code>MALABSORPTION_SYNDROME = 110;</code>
     */
    public static final int MALABSORPTION_SYNDROME_VALUE = 110;
    /**
     * <code>DIABETES_MELLITUS_TYPE_2 = 111;</code>
     */
    public static final int DIABETES_MELLITUS_TYPE_2_VALUE = 111;
    /**
     * <code>DIABETES_MELLITIS_TYPE_1 = 112;</code>
     */
    public static final int DIABETES_MELLITIS_TYPE_1_VALUE = 112;
    /**
     * <code>ANOREXIA_NERVOSA = 113;</code>
     */
    public static final int ANOREXIA_NERVOSA_VALUE = 113;
    /**
     * <code>UNDERWEIGHT = 114;</code>
     */
    public static final int UNDERWEIGHT_VALUE = 114;
    /**
     * <code>NORMAL_WEIGHT = 115;</code>
     */
    public static final int NORMAL_WEIGHT_VALUE = 115;
    /**
     * <code>OVERWEIGHT = 116;</code>
     */
    public static final int OVERWEIGHT_VALUE = 116;
    /**
     * <code>OBESITY_CLASS_1 = 117;</code>
     */
    public static final int OBESITY_CLASS_1_VALUE = 117;
    /**
     * <code>OBESITY_CLASS_2 = 118;</code>
     */
    public static final int OBESITY_CLASS_2_VALUE = 118;
    /**
     * <code>OBESITY_CLASS_3 = 119;</code>
     */
    public static final int OBESITY_CLASS_3_VALUE = 119;
    /**
     * <code>METABOLIC_OBESITY_IN_NORMAL_WEIGHT = 120;</code>
     */
    public static final int METABOLIC_OBESITY_IN_NORMAL_WEIGHT_VALUE = 120;
    /**
     * <code>PROTEIN_ENERGY_MALNUTRITION = 121;</code>
     */
    public static final int PROTEIN_ENERGY_MALNUTRITION_VALUE = 121;
    /**
     * <code>HYPOTHYROIDISM_UNSPECIFIED = 122;</code>
     */
    public static final int HYPOTHYROIDISM_UNSPECIFIED_VALUE = 122;
    /**
     * <code>HYPERTHYROIDISM_UNSPECIFIED = 123;</code>
     */
    public static final int HYPERTHYROIDISM_UNSPECIFIED_VALUE = 123;
    /**
     * <code>THYROIDITIS = 124;</code>
     */
    public static final int THYROIDITIS_VALUE = 124;
    /**
     * <code>THYROID_CANCER = 125;</code>
     */
    public static final int THYROID_CANCER_VALUE = 125;
    /**
     * <code>PARATHYROID_CANCER = 126;</code>
     */
    public static final int PARATHYROID_CANCER_VALUE = 126;
    /**
     * <code>HYPERPARATHYROID_SYNDROME = 127;</code>
     */
    public static final int HYPERPARATHYROID_SYNDROME_VALUE = 127;
    /**
     * <code>OSTEOARTHRITIS = 128;</code>
     */
    public static final int OSTEOARTHRITIS_VALUE = 128;
    /**
     * <code>RHEUMATOID_ARTHRITIS = 129;</code>
     */
    public static final int RHEUMATOID_ARTHRITIS_VALUE = 129;
    /**
     * <code>OSTEOPENIA = 130;</code>
     */
    public static final int OSTEOPENIA_VALUE = 130;
    /**
     * <code>OSTEOPOROSIS = 131;</code>
     */
    public static final int OSTEOPOROSIS_VALUE = 131;
    /**
     * <code>SEPTIC_ARTHRITIS = 132;</code>
     */
    public static final int SEPTIC_ARTHRITIS_VALUE = 132;
    /**
     * <code>GOUT = 133;</code>
     */
    public static final int GOUT_VALUE = 133;
    /**
     * <code>PSEUDO_GOUT = 134;</code>
     */
    public static final int PSEUDO_GOUT_VALUE = 134;
    /**
     * <code>MYASTHENIA_GRAVIS = 135;</code>
     */
    public static final int MYASTHENIA_GRAVIS_VALUE = 135;
    /**
     * <code>SYSTEMIC_LUPUS_ERYTHEMATOSUS = 136;</code>
     */
    public static final int SYSTEMIC_LUPUS_ERYTHEMATOSUS_VALUE = 136;
    /**
     * <code>URINARY_TRACT_INFECTION = 137;</code>
     */
    public static final int URINARY_TRACT_INFECTION_VALUE = 137;
    /**
     * <code>PYELONEPHRITIS = 138;</code>
     */
    public static final int PYELONEPHRITIS_VALUE = 138;
    /**
     * <code>BENIGN_PROSTATE_HYPERTROPHY = 139;</code>
     */
    public static final int BENIGN_PROSTATE_HYPERTROPHY_VALUE = 139;
    /**
     * <code>PROSTATE_CANCER = 140;</code>
     */
    public static final int PROSTATE_CANCER_VALUE = 140;
    /**
     * <code>RENAL_CALCULI = 141;</code>
     */
    public static final int RENAL_CALCULI_VALUE = 141;
    /**
     * <code>RENAL_FAILURE_STAGE_1 = 142;</code>
     */
    public static final int RENAL_FAILURE_STAGE_1_VALUE = 142;
    /**
     * <code>RENAL_FAILURE_STAGE_2 = 143;</code>
     */
    public static final int RENAL_FAILURE_STAGE_2_VALUE = 143;
    /**
     * <code>RENAL_FAILURE_STAGE_3A = 144;</code>
     */
    public static final int RENAL_FAILURE_STAGE_3A_VALUE = 144;
    /**
     * <code>RENAL_FAILURE_STAGE_3B = 145;</code>
     */
    public static final int RENAL_FAILURE_STAGE_3B_VALUE = 145;
    /**
     * <code>RENAL_FAILURE_STAGE_4 = 146;</code>
     */
    public static final int RENAL_FAILURE_STAGE_4_VALUE = 146;
    /**
     * <code>RENAL_FAILURE_STAGE_5 = 147;</code>
     */
    public static final int RENAL_FAILURE_STAGE_5_VALUE = 147;
    /**
     * <code>HEMODIALYSIS = 148;</code>
     */
    public static final int HEMODIALYSIS_VALUE = 148;
    /**
     * <code>PERITONEAL_DIALYSIS = 149;</code>
     */
    public static final int PERITONEAL_DIALYSIS_VALUE = 149;
    /**
     * <code>PREGNANCY = 150;</code>
     */
    public static final int PREGNANCY_VALUE = 150;
    /**
     * <code>SPONTANEOUS_ABORTION = 151;</code>
     */
    public static final int SPONTANEOUS_ABORTION_VALUE = 151;
    /**
     * <code>THERAPEUTIC_ABORATION = 152;</code>
     */
    public static final int THERAPEUTIC_ABORATION_VALUE = 152;
    /**
     * <code>INFERTILITY = 153;</code>
     */
    public static final int INFERTILITY_VALUE = 153;
    /**
     * <code>CONTRACEPTIVE_USE = 154;</code>
     */
    public static final int CONTRACEPTIVE_USE_VALUE = 154;
    /**
     * <code>OLIGOMENORRHEA = 155;</code>
     */
    public static final int OLIGOMENORRHEA_VALUE = 155;
    /**
     * <code>DYSMENORRHEA = 156;</code>
     */
    public static final int DYSMENORRHEA_VALUE = 156;
    /**
     * <code>PRIMARY_AMENORRHEA = 157;</code>
     */
    public static final int PRIMARY_AMENORRHEA_VALUE = 157;
    /**
     * <code>SECONDARY_AMENORRHEA = 158;</code>
     */
    public static final int SECONDARY_AMENORRHEA_VALUE = 158;
    /**
     * <code>ENDOMETRIOSIS = 159;</code>
     */
    public static final int ENDOMETRIOSIS_VALUE = 159;
    /**
     * <code>SURGICAL_MENOPAUSE = 160;</code>
     */
    public static final int SURGICAL_MENOPAUSE_VALUE = 160;
    /**
     * <code>EARLY_MENOPAUSE = 161;</code>
     */
    public static final int EARLY_MENOPAUSE_VALUE = 161;
    /**
     * <code>PERIMENOPAUSE = 162;</code>
     */
    public static final int PERIMENOPAUSE_VALUE = 162;
    /**
     * <code>POST_MENOPAUSE = 163;</code>
     */
    public static final int POST_MENOPAUSE_VALUE = 163;
    /**
     * <code>POST_MENOPAUSAL_BLEED = 164;</code>
     */
    public static final int POST_MENOPAUSAL_BLEED_VALUE = 164;
    /**
     * <code>BREAST_CANCER = 165;</code>
     */
    public static final int BREAST_CANCER_VALUE = 165;
    /**
     * <code>CERVICAL_CANCER = 166;</code>
     */
    public static final int CERVICAL_CANCER_VALUE = 166;
    /**
     * <code>OVARIAN_CANCER = 167;</code>
     */
    public static final int OVARIAN_CANCER_VALUE = 167;
    /**
     * <code>ERECTILE_DYSFUNCTION = 168;</code>
     */
    public static final int ERECTILE_DYSFUNCTION_VALUE = 168;
    /**
     * <code>TESTICULAR_CANCER = 169;</code>
     */
    public static final int TESTICULAR_CANCER_VALUE = 169;
    /**
     * <code>TESTICULAR_TORSION = 170;</code>
     */
    public static final int TESTICULAR_TORSION_VALUE = 170;
    /**
     * <code>TESTICULAR_PAIN = 171;</code>
     */
    public static final int TESTICULAR_PAIN_VALUE = 171;
    /**
     * <code>VAGINAL_PAIN = 172;</code>
     */
    public static final int VAGINAL_PAIN_VALUE = 172;
    /**
     * <code>ANAL_PAIN = 173;</code>
     */
    public static final int ANAL_PAIN_VALUE = 173;
    /**
     * <code>ANEMIA_UNSPECIFIED = 174;</code>
     */
    public static final int ANEMIA_UNSPECIFIED_VALUE = 174;
    /**
     * <code>IRON_DEFICIENCY_ANEMIA = 175;</code>
     */
    public static final int IRON_DEFICIENCY_ANEMIA_VALUE = 175;
    /**
     * <code>SICKLE_CELL_DISEASE = 176;</code>
     */
    public static final int SICKLE_CELL_DISEASE_VALUE = 176;
    /**
     * <code>MACROCYTIC_ANEMIA = 177;</code>
     */
    public static final int MACROCYTIC_ANEMIA_VALUE = 177;
    /**
     * <code>MICROCYTIC_ANEMIA = 178;</code>
     */
    public static final int MICROCYTIC_ANEMIA_VALUE = 178;
    /**
     * <code>LEUKEMIA = 179;</code>
     */
    public static final int LEUKEMIA_VALUE = 179;
    /**
     * <code>LYMPHOMA = 180;</code>
     */
    public static final int LYMPHOMA_VALUE = 180;
    /**
     * <code>MYELOMA = 181;</code>
     */
    public static final int MYELOMA_VALUE = 181;
    /**
     * <code>HEMOPHILIA_A = 182;</code>
     */
    public static final int HEMOPHILIA_A_VALUE = 182;
    /**
     * <code>DEPRESSION = 183;</code>
     */
    public static final int DEPRESSION_VALUE = 183;
    /**
     * <code>SCHIZOPHRENIA = 184;</code>
     */
    public static final int SCHIZOPHRENIA_VALUE = 184;
    /**
     * <code>BIPOLAR_DISORDER = 185;</code>
     */
    public static final int BIPOLAR_DISORDER_VALUE = 185;
    /**
     * <code>ANXIETY_DISORDER = 186;</code>
     */
    public static final int ANXIETY_DISORDER_VALUE = 186;
    /**
     * <code>ADDICTION = 187;</code>
     */
    public static final int ADDICTION_VALUE = 187;
    /**
     * <code>EATING_DISORDER = 188;</code>
     */
    public static final int EATING_DISORDER_VALUE = 188;
    /**
     * <code>PREMATURE_BIRTH = 189;</code>
     */
    public static final int PREMATURE_BIRTH_VALUE = 189;
    /**
     * <code>BRONCHIOLITIS = 190;</code>
     */
    public static final int BRONCHIOLITIS_VALUE = 190;
    /**
     * <code>CROUP = 191;</code>
     */
    public static final int CROUP_VALUE = 191;
    /**
     * <code>CEREBRAL_PALSY = 192;</code>
     */
    public static final int CEREBRAL_PALSY_VALUE = 192;
    /**
     * <code>FAILURE_TO_THRIVE = 193;</code>
     */
    public static final int FAILURE_TO_THRIVE_VALUE = 193;
    /**
     * <code>CHILD_ABUSE = 194;</code>
     */
    public static final int CHILD_ABUSE_VALUE = 194;
    /**
     * <code>ELDER_ABUSE = 195;</code>
     */
    public static final int ELDER_ABUSE_VALUE = 195;
    /**
     * <code>HUMAN_IMMUNIDEFICIENCY_VIRUS_INFECTION = 196;</code>
     */
    public static final int HUMAN_IMMUNIDEFICIENCY_VIRUS_INFECTION_VALUE = 196;
    /**
     * <code>ACQUIRED_IMMUNE_DEFICIENCY_SYNDROME = 197;</code>
     */
    public static final int ACQUIRED_IMMUNE_DEFICIENCY_SYNDROME_VALUE = 197;
    /**
     * <code>MALARIA = 198;</code>
     */
    public static final int MALARIA_VALUE = 198;
    /**
     * <code>CHOLERA = 199;</code>
     */
    public static final int CHOLERA_VALUE = 199;
    /**
     * <code>IMMUNIZATION = 200;</code>
     */
    public static final int IMMUNIZATION_VALUE = 200;
    /**
     * <code>ECZEMA = 201;</code>
     */
    public static final int ECZEMA_VALUE = 201;
    /**
     * <code>DERMATITIS_UNSPECIFIED = 202;</code>
     */
    public static final int DERMATITIS_UNSPECIFIED_VALUE = 202;
    /**
     * <code>PSORIASIS = 203;</code>
     */
    public static final int PSORIASIS_VALUE = 203;
    /**
     * <code>PEMPHIGUS = 204;</code>
     */
    public static final int PEMPHIGUS_VALUE = 204;
    /**
     * <code>PEMPHIGOID = 205;</code>
     */
    public static final int PEMPHIGOID_VALUE = 205;
    /**
     * <code>ERYTHEMA_MULTIFORME = 206;</code>
     */
    public static final int ERYTHEMA_MULTIFORME_VALUE = 206;
    /**
     * <code>ERYTHEMA_NODOSUM = 207;</code>
     */
    public static final int ERYTHEMA_NODOSUM_VALUE = 207;
    /**
     * <code>SQUAMOUS_CELL_SKIN_CANCER = 208;</code>
     */
    public static final int SQUAMOUS_CELL_SKIN_CANCER_VALUE = 208;
    /**
     * <code>BASASL_CELL_SKIN_CANCER = 209;</code>
     */
    public static final int BASASL_CELL_SKIN_CANCER_VALUE = 209;
    /**
     * <code>MELANOMA_SKIN_CANCER = 210;</code>
     */
    public static final int MELANOMA_SKIN_CANCER_VALUE = 210;
    /**
     * <code>ACUTE_ABDOMEN = 211;</code>
     */
    public static final int ACUTE_ABDOMEN_VALUE = 211;
    /**
     * <code>APPENDICITIS = 212;</code>
     */
    public static final int APPENDICITIS_VALUE = 212;
    /**
     * <code>DIVERTICULITIS = 213;</code>
     */
    public static final int DIVERTICULITIS_VALUE = 213;
    /**
     * <code>DIVERTICULOSIS = 214;</code>
     */
    public static final int DIVERTICULOSIS_VALUE = 214;
    /**
     * <code>CHRONIC_PANCREATITIS = 215;</code>
     */
    public static final int CHRONIC_PANCREATITIS_VALUE = 215;
    /**
     * <code>ACUTE_PANCREATITIS = 216;</code>
     */
    public static final int ACUTE_PANCREATITIS_VALUE = 216;
    /**
     * <code>ALCOHOLIC_PANCREATITIS = 217;</code>
     */
    public static final int ALCOHOLIC_PANCREATITIS_VALUE = 217;
    /**
     * <code>GALL_STONE_PANCREATITIS = 218;</code>
     */
    public static final int GALL_STONE_PANCREATITIS_VALUE = 218;
    /**
     * <code>SMALL_BOWEL_OBSTRUCTION = 219;</code>
     */
    public static final int SMALL_BOWEL_OBSTRUCTION_VALUE = 219;
    /**
     * <code>LARGE_BOWEL_OBSTRUCTION = 220;</code>
     */
    public static final int LARGE_BOWEL_OBSTRUCTION_VALUE = 220;
    /**
     * <code>INGUINAL_HERNIA = 221;</code>
     */
    public static final int INGUINAL_HERNIA_VALUE = 221;
    /**
     * <code>PERIUMBILICAL_HERNIA = 222;</code>
     */
    public static final int PERIUMBILICAL_HERNIA_VALUE = 222;
    /**
     * <code>VENTRAL_HERNIA = 223;</code>
     */
    public static final int VENTRAL_HERNIA_VALUE = 223;
    /**
     * <code>INTERNAL_HEMORRHOIDS = 224;</code>
     */
    public static final int INTERNAL_HEMORRHOIDS_VALUE = 224;
    /**
     * <code>EXTERNAL_HEMORRHOIDS = 225;</code>
     */
    public static final int EXTERNAL_HEMORRHOIDS_VALUE = 225;
    /**
     * <code>ANAL_FISSURE = 226;</code>
     */
    public static final int ANAL_FISSURE_VALUE = 226;
    /**
     * <code>GRAVES_DISEASE = 227;</code>
     */
    public static final int GRAVES_DISEASE_VALUE = 227;
    /**
     * <code>CHOLECYSTITS = 228;</code>
     */
    public static final int CHOLECYSTITS_VALUE = 228;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MedicalIssue valueOf(int value) {
      return forNumber(value);
    }

    public static MedicalIssue forNumber(int value) {
      switch (value) {
        case 0: return NO_MEDICAL_ISSUE;
        case 1: return ELEVATED_BLOOD_PRESSURE;
        case 2: return STAGE_ONE_HYPERTENSION;
        case 3: return STAGE_TWO_HYPERTENSION;
        case 4: return STAGE_THREE_HYPERTENSION;
        case 5: return HYPERTENSIVE_URGENCY;
        case 6: return HYPERTENSIVE_EMERGENCY;
        case 7: return ISCHEMIC_CORONARY_ARTERY_DISEASE;
        case 8: return NONISCHEMIC_CORONARY_ARTERY_DISEASE;
        case 9: return SYSTOLIC_HEART_FAILURE;
        case 10: return DIASTOLIC_HEART_FAILURE;
        case 11: return ATRIAL_FIBRILLATION;
        case 12: return LONG_QT_SYNDROME;
        case 13: return VENTRICULAR_TACHYCARDIA;
        case 14: return VENTRICULAR_FIBRILLATION;
        case 15: return WOLFE_PARKINSON_WHITE_SYNDROME;
        case 16: return SUPRAVENTRICULAR_TACHYCARDIA;
        case 17: return OTHER_HEART_DYSRYTHMIA;
        case 18: return DEEP_VENOUS_THROMBOEMBOLISM;
        case 19: return SUPERFICIAL_VENOUS_THROMBOEMBOLISM;
        case 20: return PULMONARY_EMBOLISM;
        case 21: return SADDLE_EMBOLISM;
        case 22: return MITRAL_STENOSIS;
        case 23: return MITRAL_REGURIGITATION;
        case 24: return AORTIC_STENOSIS;
        case 25: return AORTIC_REGURGITATION;
        case 26: return TRICUSPID_STENOSIS;
        case 27: return TRICUSPID_REGURGITATION;
        case 28: return PERIPHERAL_VASCULAR_DISEASE;
        case 29: return CHRONIC_OBSTRUCTIVE_PULMONARY_DISEASE;
        case 30: return ASTHMA;
        case 31: return SQUAMOUS_CELL_LUNG_CANCER;
        case 32: return SMALL_CELL_LUNG_CANCER;
        case 33: return ADENOCARCINOMA_LUNG_CANCER;
        case 34: return PNUEMONIA;
        case 35: return PULMONARY_TUBERCULOSIS;
        case 36: return CYSTIC_FIBROSIS;
        case 37: return DIFFUSE_INTERSTITIAL_LUNG_DISEASE;
        case 38: return PNEUMOTHORAX;
        case 39: return TENSION_PNEUMOTHORAX;
        case 40: return CEREBROVASCULAR_DISEASE;
        case 41: return HISTORY_OF_MYOCARDIAL_INFARCTION;
        case 42: return HISTORY_OF_CEREBROVASCULAR_INFARCTION;
        case 43: return EPILEPSY;
        case 44: return MENINGITIS;
        case 45: return HEAD_INJURY;
        case 46: return TRAUMATIC_BRAIN_INJRY;
        case 47: return TENSION_HEADACHE;
        case 48: return MIGRAINE_HEADACHE;
        case 49: return CLUSTER_HEADACHE;
        case 50: return THUNDERCLAP_HEADACHE;
        case 51: return SINUS_HEADACHE;
        case 52: return CAFFEINE_WITHDRAWAL_HEADACHE;
        case 53: return EXERTION_HEADACHE;
        case 54: return HYPERTENSION_HEADACHE;
        case 55: return POST_TRAUMATIC_HEADACHE;
        case 56: return CHRONIC_TOE_PAIN;
        case 57: return CHRONIC_FOOT_PAIN;
        case 58: return CHRONIC_ANKLE_PAIN;
        case 59: return CHRONIC_KNEE_PAIN;
        case 60: return CHRONIC_HIP_PAIN;
        case 61: return CHRONIC_ABDOMINAL_PAIN;
        case 62: return CHRONIC_LUMBAR_BACK_PAIN;
        case 63: return CHRONIC_CHEST_PAIN;
        case 64: return CHRONIC_THORACIC_BACK_PAIN;
        case 65: return CHRONIC_CERVICAL_SPINAL_PAIN;
        case 66: return CHRONIC_SHOULDER_PAIN;
        case 67: return CHRONIC_ELBOW_PAIN;
        case 68: return CHRONIC_WRIST_PAIN;
        case 69: return CHRONIC_HAND_PAIN;
        case 70: return CHRONIC_FINGER_PAIN;
        case 71: return ACUTE_TOE_PAIN;
        case 72: return ACUTE_FOOT_PAIN;
        case 73: return ACUTE_ANKLE_PAIN;
        case 74: return ACUTE_KNEE_PAIN;
        case 75: return ACUTE_HIP_PAIN;
        case 76: return ACUTE_ABDOMINAL_PAIN;
        case 77: return ACUTE_LUMBAR_BACK_PAIN;
        case 78: return ACUTE_CHEST_PAIN;
        case 79: return ACUTE_THORACIC_BACK_PAIN;
        case 80: return ACUTE_CERVICAL_SPINAL_PAIN;
        case 81: return ACUTE_SHOULDER_PAIN;
        case 82: return ACUTE_ELBOW_PAIN;
        case 83: return ACUTE_WRIST_PAIN;
        case 84: return ACUTE_HAND_PAIN;
        case 85: return ACUTE_FINGER_PAIN;
        case 86: return PARKINSONS_DISEASE;
        case 87: return ALZHEIMERS_DEMENTIA;
        case 88: return VASCULAR_DEMENTIA;
        case 89: return LEWY_BODY_DEMENTIA;
        case 90: return FRONTOTEMPORAL_DEMENTIA;
        case 91: return HYPOACTIVE_DELIRIUM;
        case 92: return HYPERACTIVE_DELIRIUM;
        case 93: return MULTIPLE_SCLEROSIS;
        case 94: return PROGRESSIVE_MUSCULAR_ATROPHY;
        case 95: return AMYOTRPHIC_LATERAL_SCLEROSIS;
        case 96: return PROGRESSIVE_BULBAR_PALSY;
        case 97: return PEPTIC_ULCER;
        case 98: return GASTRITIS;
        case 99: return GASTROESOPHAGEAL_REFLUX_DISEASE;
        case 100: return INFLAMMATORY_BOWEL_DISEASE;
        case 101: return ULCERATIVE_COLITIS;
        case 102: return CHRONS_DISEASE;
        case 103: return HEPATITIS_A;
        case 104: return HEPATITIS_B;
        case 105: return HEPATITIS_C;
        case 106: return HEPATITIS_D;
        case 107: return COLORECTAL_CANCER;
        case 108: return ESOPHAGEAL_CANCER;
        case 109: return GASTRIC_CANCER;
        case 110: return MALABSORPTION_SYNDROME;
        case 111: return DIABETES_MELLITUS_TYPE_2;
        case 112: return DIABETES_MELLITIS_TYPE_1;
        case 113: return ANOREXIA_NERVOSA;
        case 114: return UNDERWEIGHT;
        case 115: return NORMAL_WEIGHT;
        case 116: return OVERWEIGHT;
        case 117: return OBESITY_CLASS_1;
        case 118: return OBESITY_CLASS_2;
        case 119: return OBESITY_CLASS_3;
        case 120: return METABOLIC_OBESITY_IN_NORMAL_WEIGHT;
        case 121: return PROTEIN_ENERGY_MALNUTRITION;
        case 122: return HYPOTHYROIDISM_UNSPECIFIED;
        case 123: return HYPERTHYROIDISM_UNSPECIFIED;
        case 124: return THYROIDITIS;
        case 125: return THYROID_CANCER;
        case 126: return PARATHYROID_CANCER;
        case 127: return HYPERPARATHYROID_SYNDROME;
        case 128: return OSTEOARTHRITIS;
        case 129: return RHEUMATOID_ARTHRITIS;
        case 130: return OSTEOPENIA;
        case 131: return OSTEOPOROSIS;
        case 132: return SEPTIC_ARTHRITIS;
        case 133: return GOUT;
        case 134: return PSEUDO_GOUT;
        case 135: return MYASTHENIA_GRAVIS;
        case 136: return SYSTEMIC_LUPUS_ERYTHEMATOSUS;
        case 137: return URINARY_TRACT_INFECTION;
        case 138: return PYELONEPHRITIS;
        case 139: return BENIGN_PROSTATE_HYPERTROPHY;
        case 140: return PROSTATE_CANCER;
        case 141: return RENAL_CALCULI;
        case 142: return RENAL_FAILURE_STAGE_1;
        case 143: return RENAL_FAILURE_STAGE_2;
        case 144: return RENAL_FAILURE_STAGE_3A;
        case 145: return RENAL_FAILURE_STAGE_3B;
        case 146: return RENAL_FAILURE_STAGE_4;
        case 147: return RENAL_FAILURE_STAGE_5;
        case 148: return HEMODIALYSIS;
        case 149: return PERITONEAL_DIALYSIS;
        case 150: return PREGNANCY;
        case 151: return SPONTANEOUS_ABORTION;
        case 152: return THERAPEUTIC_ABORATION;
        case 153: return INFERTILITY;
        case 154: return CONTRACEPTIVE_USE;
        case 155: return OLIGOMENORRHEA;
        case 156: return DYSMENORRHEA;
        case 157: return PRIMARY_AMENORRHEA;
        case 158: return SECONDARY_AMENORRHEA;
        case 159: return ENDOMETRIOSIS;
        case 160: return SURGICAL_MENOPAUSE;
        case 161: return EARLY_MENOPAUSE;
        case 162: return PERIMENOPAUSE;
        case 163: return POST_MENOPAUSE;
        case 164: return POST_MENOPAUSAL_BLEED;
        case 165: return BREAST_CANCER;
        case 166: return CERVICAL_CANCER;
        case 167: return OVARIAN_CANCER;
        case 168: return ERECTILE_DYSFUNCTION;
        case 169: return TESTICULAR_CANCER;
        case 170: return TESTICULAR_TORSION;
        case 171: return TESTICULAR_PAIN;
        case 172: return VAGINAL_PAIN;
        case 173: return ANAL_PAIN;
        case 174: return ANEMIA_UNSPECIFIED;
        case 175: return IRON_DEFICIENCY_ANEMIA;
        case 176: return SICKLE_CELL_DISEASE;
        case 177: return MACROCYTIC_ANEMIA;
        case 178: return MICROCYTIC_ANEMIA;
        case 179: return LEUKEMIA;
        case 180: return LYMPHOMA;
        case 181: return MYELOMA;
        case 182: return HEMOPHILIA_A;
        case 183: return DEPRESSION;
        case 184: return SCHIZOPHRENIA;
        case 185: return BIPOLAR_DISORDER;
        case 186: return ANXIETY_DISORDER;
        case 187: return ADDICTION;
        case 188: return EATING_DISORDER;
        case 189: return PREMATURE_BIRTH;
        case 190: return BRONCHIOLITIS;
        case 191: return CROUP;
        case 192: return CEREBRAL_PALSY;
        case 193: return FAILURE_TO_THRIVE;
        case 194: return CHILD_ABUSE;
        case 195: return ELDER_ABUSE;
        case 196: return HUMAN_IMMUNIDEFICIENCY_VIRUS_INFECTION;
        case 197: return ACQUIRED_IMMUNE_DEFICIENCY_SYNDROME;
        case 198: return MALARIA;
        case 199: return CHOLERA;
        case 200: return IMMUNIZATION;
        case 201: return ECZEMA;
        case 202: return DERMATITIS_UNSPECIFIED;
        case 203: return PSORIASIS;
        case 204: return PEMPHIGUS;
        case 205: return PEMPHIGOID;
        case 206: return ERYTHEMA_MULTIFORME;
        case 207: return ERYTHEMA_NODOSUM;
        case 208: return SQUAMOUS_CELL_SKIN_CANCER;
        case 209: return BASASL_CELL_SKIN_CANCER;
        case 210: return MELANOMA_SKIN_CANCER;
        case 211: return ACUTE_ABDOMEN;
        case 212: return APPENDICITIS;
        case 213: return DIVERTICULITIS;
        case 214: return DIVERTICULOSIS;
        case 215: return CHRONIC_PANCREATITIS;
        case 216: return ACUTE_PANCREATITIS;
        case 217: return ALCOHOLIC_PANCREATITIS;
        case 218: return GALL_STONE_PANCREATITIS;
        case 219: return SMALL_BOWEL_OBSTRUCTION;
        case 220: return LARGE_BOWEL_OBSTRUCTION;
        case 221: return INGUINAL_HERNIA;
        case 222: return PERIUMBILICAL_HERNIA;
        case 223: return VENTRAL_HERNIA;
        case 224: return INTERNAL_HEMORRHOIDS;
        case 225: return EXTERNAL_HEMORRHOIDS;
        case 226: return ANAL_FISSURE;
        case 227: return GRAVES_DISEASE;
        case 228: return CHOLECYSTITS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MedicalIssue>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MedicalIssue> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MedicalIssue>() {
            public MedicalIssue findValueByNumber(int number) {
              return MedicalIssue.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ehr.medicalissues.Medicalissues.getDescriptor().getEnumTypes().get(0);
    }

    private static final MedicalIssue[] VALUES = values();

    public static MedicalIssue valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MedicalIssue(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ehr.medicalissues.MedicalIssue)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023medicalissues.proto\022\021ehr.medicalissues" +
      "*\207,\n\014MedicalIssue\022\024\n\020NO_MEDICAL_ISSUE\020\000\022" +
      "\033\n\027ELEVATED_BLOOD_PRESSURE\020\001\022\032\n\026STAGE_ON" +
      "E_HYPERTENSION\020\002\022\032\n\026STAGE_TWO_HYPERTENSI" +
      "ON\020\003\022\034\n\030STAGE_THREE_HYPERTENSION\020\004\022\030\n\024HY" +
      "PERTENSIVE_URGENCY\020\005\022\032\n\026HYPERTENSIVE_EME" +
      "RGENCY\020\006\022$\n ISCHEMIC_CORONARY_ARTERY_DIS" +
      "EASE\020\007\022\'\n#NONISCHEMIC_CORONARY_ARTERY_DI" +
      "SEASE\020\010\022\032\n\026SYSTOLIC_HEART_FAILURE\020\t\022\033\n\027D" +
      "IASTOLIC_HEART_FAILURE\020\n\022\027\n\023ATRIAL_FIBRI" +
      "LLATION\020\013\022\024\n\020LONG_QT_SYNDROME\020\014\022\033\n\027VENTR" +
      "ICULAR_TACHYCARDIA\020\r\022\034\n\030VENTRICULAR_FIBR" +
      "ILLATION\020\016\022\"\n\036WOLFE_PARKINSON_WHITE_SYND" +
      "ROME\020\017\022 \n\034SUPRAVENTRICULAR_TACHYCARDIA\020\020" +
      "\022\032\n\026OTHER_HEART_DYSRYTHMIA\020\021\022\037\n\033DEEP_VEN" +
      "OUS_THROMBOEMBOLISM\020\022\022&\n\"SUPERFICIAL_VEN" +
      "OUS_THROMBOEMBOLISM\020\023\022\026\n\022PULMONARY_EMBOL" +
      "ISM\020\024\022\023\n\017SADDLE_EMBOLISM\020\025\022\023\n\017MITRAL_STE" +
      "NOSIS\020\026\022\031\n\025MITRAL_REGURIGITATION\020\027\022\023\n\017AO" +
      "RTIC_STENOSIS\020\030\022\030\n\024AORTIC_REGURGITATION\020" +
      "\031\022\026\n\022TRICUSPID_STENOSIS\020\032\022\033\n\027TRICUSPID_R" +
      "EGURGITATION\020\033\022\037\n\033PERIPHERAL_VASCULAR_DI" +
      "SEASE\020\034\022)\n%CHRONIC_OBSTRUCTIVE_PULMONARY" +
      "_DISEASE\020\035\022\n\n\006ASTHMA\020\036\022\035\n\031SQUAMOUS_CELL_" +
      "LUNG_CANCER\020\037\022\032\n\026SMALL_CELL_LUNG_CANCER\020" +
      " \022\036\n\032ADENOCARCINOMA_LUNG_CANCER\020!\022\r\n\tPNU" +
      "EMONIA\020\"\022\032\n\026PULMONARY_TUBERCULOSIS\020#\022\023\n\017" +
      "CYSTIC_FIBROSIS\020$\022%\n!DIFFUSE_INTERSTITIA" +
      "L_LUNG_DISEASE\020%\022\020\n\014PNEUMOTHORAX\020&\022\030\n\024TE" +
      "NSION_PNEUMOTHORAX\020\'\022\033\n\027CEREBROVASCULAR_" +
      "DISEASE\020(\022$\n HISTORY_OF_MYOCARDIAL_INFAR" +
      "CTION\020)\022)\n%HISTORY_OF_CEREBROVASCULAR_IN" +
      "FARCTION\020*\022\014\n\010EPILEPSY\020+\022\016\n\nMENINGITIS\020," +
      "\022\017\n\013HEAD_INJURY\020-\022\031\n\025TRAUMATIC_BRAIN_INJ" +
      "RY\020.\022\024\n\020TENSION_HEADACHE\020/\022\025\n\021MIGRAINE_H" +
      "EADACHE\0200\022\024\n\020CLUSTER_HEADACHE\0201\022\030\n\024THUND" +
      "ERCLAP_HEADACHE\0202\022\022\n\016SINUS_HEADACHE\0203\022 \n" +
      "\034CAFFEINE_WITHDRAWAL_HEADACHE\0204\022\025\n\021EXERT" +
      "ION_HEADACHE\0205\022\031\n\025HYPERTENSION_HEADACHE\020" +
      "6\022\033\n\027POST_TRAUMATIC_HEADACHE\0207\022\024\n\020CHRONI" +
      "C_TOE_PAIN\0208\022\025\n\021CHRONIC_FOOT_PAIN\0209\022\026\n\022C" +
      "HRONIC_ANKLE_PAIN\020:\022\025\n\021CHRONIC_KNEE_PAIN" +
      "\020;\022\024\n\020CHRONIC_HIP_PAIN\020<\022\032\n\026CHRONIC_ABDO" +
      "MINAL_PAIN\020=\022\034\n\030CHRONIC_LUMBAR_BACK_PAIN" +
      "\020>\022\026\n\022CHRONIC_CHEST_PAIN\020?\022\036\n\032CHRONIC_TH" +
      "ORACIC_BACK_PAIN\020@\022 \n\034CHRONIC_CERVICAL_S" +
      "PINAL_PAIN\020A\022\031\n\025CHRONIC_SHOULDER_PAIN\020B\022" +
      "\026\n\022CHRONIC_ELBOW_PAIN\020C\022\026\n\022CHRONIC_WRIST" +
      "_PAIN\020D\022\025\n\021CHRONIC_HAND_PAIN\020E\022\027\n\023CHRONI" +
      "C_FINGER_PAIN\020F\022\022\n\016ACUTE_TOE_PAIN\020G\022\023\n\017A" +
      "CUTE_FOOT_PAIN\020H\022\024\n\020ACUTE_ANKLE_PAIN\020I\022\023" +
      "\n\017ACUTE_KNEE_PAIN\020J\022\022\n\016ACUTE_HIP_PAIN\020K\022" +
      "\030\n\024ACUTE_ABDOMINAL_PAIN\020L\022\032\n\026ACUTE_LUMBA" +
      "R_BACK_PAIN\020M\022\024\n\020ACUTE_CHEST_PAIN\020N\022\034\n\030A" +
      "CUTE_THORACIC_BACK_PAIN\020O\022\036\n\032ACUTE_CERVI" +
      "CAL_SPINAL_PAIN\020P\022\027\n\023ACUTE_SHOULDER_PAIN" +
      "\020Q\022\024\n\020ACUTE_ELBOW_PAIN\020R\022\024\n\020ACUTE_WRIST_" +
      "PAIN\020S\022\023\n\017ACUTE_HAND_PAIN\020T\022\025\n\021ACUTE_FIN" +
      "GER_PAIN\020U\022\026\n\022PARKINSONS_DISEASE\020V\022\027\n\023AL" +
      "ZHEIMERS_DEMENTIA\020W\022\025\n\021VASCULAR_DEMENTIA" +
      "\020X\022\026\n\022LEWY_BODY_DEMENTIA\020Y\022\033\n\027FRONTOTEMP" +
      "ORAL_DEMENTIA\020Z\022\027\n\023HYPOACTIVE_DELIRIUM\020[" +
      "\022\030\n\024HYPERACTIVE_DELIRIUM\020\\\022\026\n\022MULTIPLE_S" +
      "CLEROSIS\020]\022 \n\034PROGRESSIVE_MUSCULAR_ATROP" +
      "HY\020^\022 \n\034AMYOTRPHIC_LATERAL_SCLEROSIS\020_\022\034" +
      "\n\030PROGRESSIVE_BULBAR_PALSY\020`\022\020\n\014PEPTIC_U" +
      "LCER\020a\022\r\n\tGASTRITIS\020b\022#\n\037GASTROESOPHAGEA" +
      "L_REFLUX_DISEASE\020c\022\036\n\032INFLAMMATORY_BOWEL" +
      "_DISEASE\020d\022\026\n\022ULCERATIVE_COLITIS\020e\022\022\n\016CH" +
      "RONS_DISEASE\020f\022\017\n\013HEPATITIS_A\020g\022\017\n\013HEPAT" +
      "ITIS_B\020h\022\017\n\013HEPATITIS_C\020i\022\017\n\013HEPATITIS_D" +
      "\020j\022\025\n\021COLORECTAL_CANCER\020k\022\025\n\021ESOPHAGEAL_" +
      "CANCER\020l\022\022\n\016GASTRIC_CANCER\020m\022\032\n\026MALABSOR" +
      "PTION_SYNDROME\020n\022\034\n\030DIABETES_MELLITUS_TY" +
      "PE_2\020o\022\034\n\030DIABETES_MELLITIS_TYPE_1\020p\022\024\n\020" +
      "ANOREXIA_NERVOSA\020q\022\017\n\013UNDERWEIGHT\020r\022\021\n\rN" +
      "ORMAL_WEIGHT\020s\022\016\n\nOVERWEIGHT\020t\022\023\n\017OBESIT" +
      "Y_CLASS_1\020u\022\023\n\017OBESITY_CLASS_2\020v\022\023\n\017OBES" +
      "ITY_CLASS_3\020w\022&\n\"METABOLIC_OBESITY_IN_NO" +
      "RMAL_WEIGHT\020x\022\037\n\033PROTEIN_ENERGY_MALNUTRI" +
      "TION\020y\022\036\n\032HYPOTHYROIDISM_UNSPECIFIED\020z\022\037" +
      "\n\033HYPERTHYROIDISM_UNSPECIFIED\020{\022\017\n\013THYRO" +
      "IDITIS\020|\022\022\n\016THYROID_CANCER\020}\022\026\n\022PARATHYR" +
      "OID_CANCER\020~\022\035\n\031HYPERPARATHYROID_SYNDROM" +
      "E\020\177\022\023\n\016OSTEOARTHRITIS\020\200\001\022\031\n\024RHEUMATOID_A" +
      "RTHRITIS\020\201\001\022\017\n\nOSTEOPENIA\020\202\001\022\021\n\014OSTEOPOR" +
      "OSIS\020\203\001\022\025\n\020SEPTIC_ARTHRITIS\020\204\001\022\t\n\004GOUT\020\205" +
      "\001\022\020\n\013PSEUDO_GOUT\020\206\001\022\026\n\021MYASTHENIA_GRAVIS" +
      "\020\207\001\022!\n\034SYSTEMIC_LUPUS_ERYTHEMATOSUS\020\210\001\022\034" +
      "\n\027URINARY_TRACT_INFECTION\020\211\001\022\023\n\016PYELONEP" +
      "HRITIS\020\212\001\022 \n\033BENIGN_PROSTATE_HYPERTROPHY" +
      "\020\213\001\022\024\n\017PROSTATE_CANCER\020\214\001\022\022\n\rRENAL_CALCU" +
      "LI\020\215\001\022\032\n\025RENAL_FAILURE_STAGE_1\020\216\001\022\032\n\025REN" +
      "AL_FAILURE_STAGE_2\020\217\001\022\033\n\026RENAL_FAILURE_S" +
      "TAGE_3A\020\220\001\022\033\n\026RENAL_FAILURE_STAGE_3B\020\221\001\022" +
      "\032\n\025RENAL_FAILURE_STAGE_4\020\222\001\022\032\n\025RENAL_FAI" +
      "LURE_STAGE_5\020\223\001\022\021\n\014HEMODIALYSIS\020\224\001\022\030\n\023PE" +
      "RITONEAL_DIALYSIS\020\225\001\022\016\n\tPREGNANCY\020\226\001\022\031\n\024" +
      "SPONTANEOUS_ABORTION\020\227\001\022\032\n\025THERAPEUTIC_A" +
      "BORATION\020\230\001\022\020\n\013INFERTILITY\020\231\001\022\026\n\021CONTRAC" +
      "EPTIVE_USE\020\232\001\022\023\n\016OLIGOMENORRHEA\020\233\001\022\021\n\014DY" +
      "SMENORRHEA\020\234\001\022\027\n\022PRIMARY_AMENORRHEA\020\235\001\022\031" +
      "\n\024SECONDARY_AMENORRHEA\020\236\001\022\022\n\rENDOMETRIOS" +
      "IS\020\237\001\022\027\n\022SURGICAL_MENOPAUSE\020\240\001\022\024\n\017EARLY_" +
      "MENOPAUSE\020\241\001\022\022\n\rPERIMENOPAUSE\020\242\001\022\023\n\016POST" +
      "_MENOPAUSE\020\243\001\022\032\n\025POST_MENOPAUSAL_BLEED\020\244" +
      "\001\022\022\n\rBREAST_CANCER\020\245\001\022\024\n\017CERVICAL_CANCER" +
      "\020\246\001\022\023\n\016OVARIAN_CANCER\020\247\001\022\031\n\024ERECTILE_DYS" +
      "FUNCTION\020\250\001\022\026\n\021TESTICULAR_CANCER\020\251\001\022\027\n\022T" +
      "ESTICULAR_TORSION\020\252\001\022\024\n\017TESTICULAR_PAIN\020" +
      "\253\001\022\021\n\014VAGINAL_PAIN\020\254\001\022\016\n\tANAL_PAIN\020\255\001\022\027\n" +
      "\022ANEMIA_UNSPECIFIED\020\256\001\022\033\n\026IRON_DEFICIENC" +
      "Y_ANEMIA\020\257\001\022\030\n\023SICKLE_CELL_DISEASE\020\260\001\022\026\n" +
      "\021MACROCYTIC_ANEMIA\020\261\001\022\026\n\021MICROCYTIC_ANEM" +
      "IA\020\262\001\022\r\n\010LEUKEMIA\020\263\001\022\r\n\010LYMPHOMA\020\264\001\022\014\n\007M" +
      "YELOMA\020\265\001\022\021\n\014HEMOPHILIA_A\020\266\001\022\017\n\nDEPRESSI" +
      "ON\020\267\001\022\022\n\rSCHIZOPHRENIA\020\270\001\022\025\n\020BIPOLAR_DIS" +
      "ORDER\020\271\001\022\025\n\020ANXIETY_DISORDER\020\272\001\022\016\n\tADDIC" +
      "TION\020\273\001\022\024\n\017EATING_DISORDER\020\274\001\022\024\n\017PREMATU" +
      "RE_BIRTH\020\275\001\022\022\n\rBRONCHIOLITIS\020\276\001\022\n\n\005CROUP" +
      "\020\277\001\022\023\n\016CEREBRAL_PALSY\020\300\001\022\026\n\021FAILURE_TO_T" +
      "HRIVE\020\301\001\022\020\n\013CHILD_ABUSE\020\302\001\022\020\n\013ELDER_ABUS" +
      "E\020\303\001\022+\n&HUMAN_IMMUNIDEFICIENCY_VIRUS_INF" +
      "ECTION\020\304\001\022(\n#ACQUIRED_IMMUNE_DEFICIENCY_" +
      "SYNDROME\020\305\001\022\014\n\007MALARIA\020\306\001\022\014\n\007CHOLERA\020\307\001\022" +
      "\021\n\014IMMUNIZATION\020\310\001\022\013\n\006ECZEMA\020\311\001\022\033\n\026DERMA" +
      "TITIS_UNSPECIFIED\020\312\001\022\016\n\tPSORIASIS\020\313\001\022\016\n\t" +
      "PEMPHIGUS\020\314\001\022\017\n\nPEMPHIGOID\020\315\001\022\030\n\023ERYTHEM" +
      "A_MULTIFORME\020\316\001\022\025\n\020ERYTHEMA_NODOSUM\020\317\001\022\036" +
      "\n\031SQUAMOUS_CELL_SKIN_CANCER\020\320\001\022\034\n\027BASASL" +
      "_CELL_SKIN_CANCER\020\321\001\022\031\n\024MELANOMA_SKIN_CA" +
      "NCER\020\322\001\022\022\n\rACUTE_ABDOMEN\020\323\001\022\021\n\014APPENDICI" +
      "TIS\020\324\001\022\023\n\016DIVERTICULITIS\020\325\001\022\023\n\016DIVERTICU" +
      "LOSIS\020\326\001\022\031\n\024CHRONIC_PANCREATITIS\020\327\001\022\027\n\022A" +
      "CUTE_PANCREATITIS\020\330\001\022\033\n\026ALCOHOLIC_PANCRE" +
      "ATITIS\020\331\001\022\034\n\027GALL_STONE_PANCREATITIS\020\332\001\022" +
      "\034\n\027SMALL_BOWEL_OBSTRUCTION\020\333\001\022\034\n\027LARGE_B" +
      "OWEL_OBSTRUCTION\020\334\001\022\024\n\017INGUINAL_HERNIA\020\335" +
      "\001\022\031\n\024PERIUMBILICAL_HERNIA\020\336\001\022\023\n\016VENTRAL_" +
      "HERNIA\020\337\001\022\031\n\024INTERNAL_HEMORRHOIDS\020\340\001\022\031\n\024" +
      "EXTERNAL_HEMORRHOIDS\020\341\001\022\021\n\014ANAL_FISSURE\020" +
      "\342\001\022\023\n\016GRAVES_DISEASE\020\343\001\022\021\n\014CHOLECYSTITS\020" +
      "\344\001B\007Z\005ehrpbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
