// Code generated by protoc-gen-go. DO NOT EDIT.
// source: note.proto

package ehrpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FragmentTopic int32

const (
	FragmentTopic_NO_TOPIC          FragmentTopic = 0
	FragmentTopic_SUBJECTIVE        FragmentTopic = 1
	FragmentTopic_REVIEW_OF_SYSTEMS FragmentTopic = 2
	FragmentTopic_MEDICAL_HISTORY   FragmentTopic = 3
	FragmentTopic_ALLERGIES         FragmentTopic = 4
	FragmentTopic_MEDICATIONS       FragmentTopic = 5
	FragmentTopic_FAMILY_HISTORY    FragmentTopic = 6
	FragmentTopic_SOCIAL_HISTORY    FragmentTopic = 7
	FragmentTopic_VITALS            FragmentTopic = 8
	FragmentTopic_PHYSICAL_EXAM     FragmentTopic = 9
	FragmentTopic_LABORATORY_DATA   FragmentTopic = 10
	FragmentTopic_MEDICAL_PROBLEM   FragmentTopic = 11
)

var FragmentTopic_name = map[int32]string{
	0:  "NO_TOPIC",
	1:  "SUBJECTIVE",
	2:  "REVIEW_OF_SYSTEMS",
	3:  "MEDICAL_HISTORY",
	4:  "ALLERGIES",
	5:  "MEDICATIONS",
	6:  "FAMILY_HISTORY",
	7:  "SOCIAL_HISTORY",
	8:  "VITALS",
	9:  "PHYSICAL_EXAM",
	10: "LABORATORY_DATA",
	11: "MEDICAL_PROBLEM",
}
var FragmentTopic_value = map[string]int32{
	"NO_TOPIC":          0,
	"SUBJECTIVE":        1,
	"REVIEW_OF_SYSTEMS": 2,
	"MEDICAL_HISTORY":   3,
	"ALLERGIES":         4,
	"MEDICATIONS":       5,
	"FAMILY_HISTORY":    6,
	"SOCIAL_HISTORY":    7,
	"VITALS":            8,
	"PHYSICAL_EXAM":     9,
	"LABORATORY_DATA":   10,
	"MEDICAL_PROBLEM":   11,
}

func (x FragmentTopic) String() string {
	return proto.EnumName(FragmentTopic_name, int32(x))
}
func (FragmentTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_note_65925d73012e8376, []int{0}
}

type FragmentPriority int32

const (
	FragmentPriority_NO_PRIORITY FragmentPriority = 0
	FragmentPriority_HIGH        FragmentPriority = 1
	FragmentPriority_NORMAL      FragmentPriority = 2
	FragmentPriority_LOW         FragmentPriority = 3
)

var FragmentPriority_name = map[int32]string{
	0: "NO_PRIORITY",
	1: "HIGH",
	2: "NORMAL",
	3: "LOW",
}
var FragmentPriority_value = map[string]int32{
	"NO_PRIORITY": 0,
	"HIGH":        1,
	"NORMAL":      2,
	"LOW":         3,
}

func (x FragmentPriority) String() string {
	return proto.EnumName(FragmentPriority_name, int32(x))
}
func (FragmentPriority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_note_65925d73012e8376, []int{1}
}

type NoteFragmentStatus int32

const (
	NoteFragmentStatus_NO_STATUS  NoteFragmentStatus = 0
	NoteFragmentStatus_INCOMPLETE NoteFragmentStatus = 1
	NoteFragmentStatus_ACTIVE     NoteFragmentStatus = 2
	NoteFragmentStatus_REPLACED   NoteFragmentStatus = 3
)

var NoteFragmentStatus_name = map[int32]string{
	0: "NO_STATUS",
	1: "INCOMPLETE",
	2: "ACTIVE",
	3: "REPLACED",
}
var NoteFragmentStatus_value = map[string]int32{
	"NO_STATUS":  0,
	"INCOMPLETE": 1,
	"ACTIVE":     2,
	"REPLACED":   3,
}

func (x NoteFragmentStatus) String() string {
	return proto.EnumName(NoteFragmentStatus_name, int32(x))
}
func (NoteFragmentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_note_65925d73012e8376, []int{2}
}

type NoteType int32

const (
	NoteType_NO_NOTE_TYPE                 NoteType = 0
	NoteType_FOLLOW_UP                    NoteType = 1
	NoteType_PHONE_CALL                   NoteType = 2
	NoteType_CONTINUED_CARE_DOCUMENTATION NoteType = 4
	NoteType_REFILL_DOCUMENTATION         NoteType = 5
	NoteType_INTAKE                       NoteType = 6
	NoteType_PROCEDURE                    NoteType = 7
	NoteType_HISTORY_AND_PHYSICAL         NoteType = 8
)

var NoteType_name = map[int32]string{
	0: "NO_NOTE_TYPE",
	1: "FOLLOW_UP",
	2: "PHONE_CALL",
	4: "CONTINUED_CARE_DOCUMENTATION",
	5: "REFILL_DOCUMENTATION",
	6: "INTAKE",
	7: "PROCEDURE",
	8: "HISTORY_AND_PHYSICAL",
}
var NoteType_value = map[string]int32{
	"NO_NOTE_TYPE":                 0,
	"FOLLOW_UP":                    1,
	"PHONE_CALL":                   2,
	"CONTINUED_CARE_DOCUMENTATION": 4,
	"REFILL_DOCUMENTATION":         5,
	"INTAKE":                       6,
	"PROCEDURE":                    7,
	"HISTORY_AND_PHYSICAL":         8,
}

func (x NoteType) String() string {
	return proto.EnumName(NoteType_name, int32(x))
}
func (NoteType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_note_65925d73012e8376, []int{3}
}

type Note struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DateCreated          *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date_created,json=dateCreated,proto3" json:"date_created,omitempty"`
	NoteGuid             string               `protobuf:"bytes,3,opt,name=note_guid,json=noteGuid,proto3" json:"note_guid,omitempty"`
	VisitGuid            string               `protobuf:"bytes,4,opt,name=visit_guid,json=visitGuid,proto3" json:"visit_guid,omitempty"`
	AuthorGuid           string               `protobuf:"bytes,5,opt,name=author_guid,json=authorGuid,proto3" json:"author_guid,omitempty"`
	PatientGuid          string               `protobuf:"bytes,6,opt,name=patient_guid,json=patientGuid,proto3" json:"patient_guid,omitempty"`
	Type                 NoteType             `protobuf:"varint,7,opt,name=type,proto3,enum=ehr.note.NoteType" json:"type,omitempty"`
	Fragments            []*NoteFragment      `protobuf:"bytes,8,rep,name=fragments,proto3" json:"fragments,omitempty"`
	Tags                 []string             `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Note) Reset()         { *m = Note{} }
func (m *Note) String() string { return proto.CompactTextString(m) }
func (*Note) ProtoMessage()    {}
func (*Note) Descriptor() ([]byte, []int) {
	return fileDescriptor_note_65925d73012e8376, []int{0}
}
func (m *Note) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Note.Unmarshal(m, b)
}
func (m *Note) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Note.Marshal(b, m, deterministic)
}
func (dst *Note) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Note.Merge(dst, src)
}
func (m *Note) XXX_Size() int {
	return xxx_messageInfo_Note.Size(m)
}
func (m *Note) XXX_DiscardUnknown() {
	xxx_messageInfo_Note.DiscardUnknown(m)
}

var xxx_messageInfo_Note proto.InternalMessageInfo

func (m *Note) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Note) GetDateCreated() *timestamp.Timestamp {
	if m != nil {
		return m.DateCreated
	}
	return nil
}

func (m *Note) GetNoteGuid() string {
	if m != nil {
		return m.NoteGuid
	}
	return ""
}

func (m *Note) GetVisitGuid() string {
	if m != nil {
		return m.VisitGuid
	}
	return ""
}

func (m *Note) GetAuthorGuid() string {
	if m != nil {
		return m.AuthorGuid
	}
	return ""
}

func (m *Note) GetPatientGuid() string {
	if m != nil {
		return m.PatientGuid
	}
	return ""
}

func (m *Note) GetType() NoteType {
	if m != nil {
		return m.Type
	}
	return NoteType_NO_NOTE_TYPE
}

func (m *Note) GetFragments() []*NoteFragment {
	if m != nil {
		return m.Fragments
	}
	return nil
}

func (m *Note) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type NoteFragment struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DateCreated          *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date_created,json=dateCreated,proto3" json:"date_created,omitempty"`
	NoteFragmentGuid     string               `protobuf:"bytes,3,opt,name=note_fragment_guid,json=noteFragmentGuid,proto3" json:"note_fragment_guid,omitempty"`
	NoteGuid             string               `protobuf:"bytes,4,opt,name=note_guid,json=noteGuid,proto3" json:"note_guid,omitempty"`
	IssueGuid            string               `protobuf:"bytes,5,opt,name=issue_guid,json=issueGuid,proto3" json:"issue_guid,omitempty"`
	Icd_10Code           string               `protobuf:"bytes,6,opt,name=icd_10_code,json=icd10Code,proto3" json:"icd_10_code,omitempty"`
	Icd_10Long           string               `protobuf:"bytes,7,opt,name=icd_10_long,json=icd10Long,proto3" json:"icd_10_long,omitempty"`
	Description          string               `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Status               NoteFragmentStatus   `protobuf:"varint,9,opt,name=status,proto3,enum=ehr.note.NoteFragmentStatus" json:"status,omitempty"`
	Priority             FragmentPriority     `protobuf:"varint,10,opt,name=priority,proto3,enum=ehr.note.FragmentPriority" json:"priority,omitempty"`
	Topic                FragmentTopic        `protobuf:"varint,11,opt,name=topic,proto3,enum=ehr.note.FragmentTopic" json:"topic,omitempty"`
	MarkdownContent      string               `protobuf:"bytes,12,opt,name=markdown_content,json=markdownContent,proto3" json:"markdown_content,omitempty"`
	Tags                 []string             `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NoteFragment) Reset()         { *m = NoteFragment{} }
func (m *NoteFragment) String() string { return proto.CompactTextString(m) }
func (*NoteFragment) ProtoMessage()    {}
func (*NoteFragment) Descriptor() ([]byte, []int) {
	return fileDescriptor_note_65925d73012e8376, []int{1}
}
func (m *NoteFragment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoteFragment.Unmarshal(m, b)
}
func (m *NoteFragment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoteFragment.Marshal(b, m, deterministic)
}
func (dst *NoteFragment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoteFragment.Merge(dst, src)
}
func (m *NoteFragment) XXX_Size() int {
	return xxx_messageInfo_NoteFragment.Size(m)
}
func (m *NoteFragment) XXX_DiscardUnknown() {
	xxx_messageInfo_NoteFragment.DiscardUnknown(m)
}

var xxx_messageInfo_NoteFragment proto.InternalMessageInfo

func (m *NoteFragment) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NoteFragment) GetDateCreated() *timestamp.Timestamp {
	if m != nil {
		return m.DateCreated
	}
	return nil
}

func (m *NoteFragment) GetNoteFragmentGuid() string {
	if m != nil {
		return m.NoteFragmentGuid
	}
	return ""
}

func (m *NoteFragment) GetNoteGuid() string {
	if m != nil {
		return m.NoteGuid
	}
	return ""
}

func (m *NoteFragment) GetIssueGuid() string {
	if m != nil {
		return m.IssueGuid
	}
	return ""
}

func (m *NoteFragment) GetIcd_10Code() string {
	if m != nil {
		return m.Icd_10Code
	}
	return ""
}

func (m *NoteFragment) GetIcd_10Long() string {
	if m != nil {
		return m.Icd_10Long
	}
	return ""
}

func (m *NoteFragment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NoteFragment) GetStatus() NoteFragmentStatus {
	if m != nil {
		return m.Status
	}
	return NoteFragmentStatus_NO_STATUS
}

func (m *NoteFragment) GetPriority() FragmentPriority {
	if m != nil {
		return m.Priority
	}
	return FragmentPriority_NO_PRIORITY
}

func (m *NoteFragment) GetTopic() FragmentTopic {
	if m != nil {
		return m.Topic
	}
	return FragmentTopic_NO_TOPIC
}

func (m *NoteFragment) GetMarkdownContent() string {
	if m != nil {
		return m.MarkdownContent
	}
	return ""
}

func (m *NoteFragment) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*Note)(nil), "ehr.note.Note")
	proto.RegisterType((*NoteFragment)(nil), "ehr.note.NoteFragment")
	proto.RegisterEnum("ehr.note.FragmentTopic", FragmentTopic_name, FragmentTopic_value)
	proto.RegisterEnum("ehr.note.FragmentPriority", FragmentPriority_name, FragmentPriority_value)
	proto.RegisterEnum("ehr.note.NoteFragmentStatus", NoteFragmentStatus_name, NoteFragmentStatus_value)
	proto.RegisterEnum("ehr.note.NoteType", NoteType_name, NoteType_value)
}

func init() { proto.RegisterFile("note.proto", fileDescriptor_note_65925d73012e8376) }

var fileDescriptor_note_65925d73012e8376 = []byte{
	// 841 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xdb, 0x72, 0xe3, 0x34,
	0x1c, 0xc6, 0xeb, 0x9c, 0x6a, 0xff, 0x9d, 0xb6, 0x5a, 0x2d, 0x07, 0x4f, 0x59, 0xd8, 0xb0, 0x17,
	0x4c, 0xe8, 0x40, 0x76, 0xb7, 0xec, 0x70, 0xc7, 0x85, 0xeb, 0xa8, 0x8d, 0xc1, 0xb1, 0x3c, 0xb2,
	0xd3, 0x12, 0x6e, 0x34, 0x6e, 0xac, 0x4d, 0x3d, 0x34, 0x76, 0xc6, 0x51, 0x60, 0xfa, 0x00, 0xbc,
	0x0d, 0xef, 0xc1, 0xbb, 0xf0, 0x14, 0x8c, 0xe4, 0xa4, 0x4d, 0xb7, 0x5c, 0xee, 0x5d, 0xf2, 0x7d,
	0xdf, 0xff, 0xa0, 0x9f, 0x94, 0x00, 0x14, 0xa5, 0x14, 0x83, 0x65, 0x55, 0xca, 0x12, 0x9b, 0xe2,
	0xa6, 0x1a, 0xa8, 0xef, 0xc7, 0x2f, 0xe7, 0x65, 0x39, 0xbf, 0x15, 0xaf, 0xb5, 0x7e, 0xbd, 0x7e,
	0xff, 0x5a, 0xe6, 0x0b, 0xb1, 0x92, 0xe9, 0x62, 0x59, 0x47, 0x8f, 0x9f, 0x2f, 0x44, 0x96, 0xcf,
	0xd2, 0xdb, 0x7c, 0xb5, 0x5a, 0x8b, 0x55, 0x2d, 0xbe, 0xfa, 0xa7, 0x01, 0xad, 0xb0, 0x94, 0x02,
	0x1f, 0x42, 0x23, 0xcf, 0x1c, 0xa3, 0x67, 0xf4, 0xdb, 0xac, 0x91, 0x67, 0xf8, 0x27, 0xe8, 0x66,
	0xa9, 0x14, 0x7c, 0x56, 0x89, 0x54, 0x8a, 0xcc, 0x69, 0xf4, 0x8c, 0xbe, 0x7d, 0x7a, 0x3c, 0xa8,
	0xa7, 0x0c, 0xb6, 0x53, 0x06, 0xc9, 0x76, 0x0a, 0xb3, 0x55, 0xde, 0xab, 0xe3, 0xf8, 0x0b, 0xb0,
	0xd4, 0x56, 0x7c, 0xbe, 0xce, 0x33, 0xa7, 0xd9, 0x33, 0xfa, 0x16, 0x33, 0x95, 0x70, 0xb1, 0xce,
	0x33, 0xfc, 0x25, 0xc0, 0x1f, 0xf9, 0x2a, 0x97, 0xb5, 0xdb, 0xd2, 0xae, 0xa5, 0x15, 0x6d, 0xbf,
	0x04, 0x3b, 0x5d, 0xcb, 0x9b, 0xb2, 0xaa, 0xfd, 0xb6, 0xf6, 0xa1, 0x96, 0x74, 0xe0, 0x6b, 0xe8,
	0x2e, 0x53, 0x99, 0x8b, 0x62, 0xd3, 0xa1, 0xa3, 0x13, 0xf6, 0x46, 0xd3, 0x91, 0x6f, 0xa0, 0x25,
	0xef, 0x96, 0xc2, 0xd9, 0xef, 0x19, 0xfd, 0xc3, 0x53, 0x3c, 0xd8, 0x62, 0x1a, 0xa8, 0xc3, 0x26,
	0x77, 0x4b, 0xc1, 0xb4, 0x8f, 0xdf, 0x81, 0xf5, 0xbe, 0x4a, 0xe7, 0x0b, 0x51, 0xc8, 0x95, 0x63,
	0xf6, 0x9a, 0x7d, 0xfb, 0xf4, 0xb3, 0xc7, 0xe1, 0xf3, 0x8d, 0xcd, 0x1e, 0x82, 0x18, 0x43, 0x4b,
	0xa6, 0xf3, 0x95, 0x63, 0xf5, 0x9a, 0x7d, 0x8b, 0xe9, 0xcf, 0xaf, 0xfe, 0x6a, 0x41, 0x77, 0x37,
	0xff, 0xb1, 0x89, 0x7e, 0x07, 0x58, 0x13, 0xdd, 0x6e, 0xb1, 0x8b, 0x16, 0x15, 0x3b, 0x83, 0xf5,
	0xf9, 0x1f, 0xf1, 0x6f, 0x3d, 0xe5, 0xaf, 0x1f, 0xc1, 0x2e, 0x5f, 0x4b, 0x2b, 0xda, 0xfe, 0x0a,
	0xec, 0x7c, 0x96, 0xf1, 0xb7, 0x6f, 0xf8, 0xac, 0xcc, 0xc4, 0x86, 0xae, 0x95, 0xcf, 0xb2, 0xb7,
	0x6f, 0xbc, 0x32, 0x13, 0x3b, 0xfe, 0x6d, 0x59, 0xcc, 0x35, 0xe2, 0xad, 0x1f, 0x94, 0xc5, 0x1c,
	0xf7, 0xc0, 0xce, 0xc4, 0x6a, 0x56, 0xe5, 0x4b, 0x99, 0x97, 0x85, 0x63, 0xd6, 0xb7, 0xb3, 0x23,
	0xe1, 0x77, 0xd0, 0x59, 0xc9, 0x54, 0xae, 0x15, 0x41, 0x75, 0x3f, 0x2f, 0xfe, 0x1f, 0x79, 0xac,
	0x33, 0x6c, 0x93, 0xc5, 0x3f, 0x82, 0xb9, 0xac, 0xf2, 0xb2, 0xca, 0xe5, 0x9d, 0x03, 0xba, 0xee,
	0xf8, 0xa1, 0x6e, 0x5b, 0x13, 0x6d, 0x12, 0xec, 0x3e, 0x8b, 0xbf, 0x87, 0xb6, 0x2c, 0x97, 0xf9,
	0xcc, 0xb1, 0x75, 0xd1, 0xe7, 0x4f, 0x8b, 0x12, 0x65, 0xb3, 0x3a, 0x85, 0xbf, 0x05, 0xb4, 0x48,
	0xab, 0xdf, 0xb3, 0xf2, 0xcf, 0x82, 0xcf, 0xca, 0x42, 0x8a, 0x42, 0x3a, 0x5d, 0x7d, 0x86, 0xa3,
	0xad, 0xee, 0xd5, 0xf2, 0xfd, 0x3b, 0x38, 0x78, 0x78, 0x07, 0x27, 0xff, 0x1a, 0x70, 0xf0, 0xa8,
	0x2f, 0xee, 0x82, 0x19, 0x52, 0x9e, 0xd0, 0xc8, 0xf7, 0xd0, 0x1e, 0x3e, 0x04, 0x88, 0x27, 0x67,
	0x3f, 0x13, 0x2f, 0xf1, 0x2f, 0x09, 0x32, 0xf0, 0xa7, 0xf0, 0x8c, 0x91, 0x4b, 0x9f, 0x5c, 0x71,
	0x7a, 0xce, 0xe3, 0x69, 0x9c, 0x90, 0x71, 0x8c, 0x1a, 0xf8, 0x39, 0x1c, 0x8d, 0xc9, 0xd0, 0xf7,
	0xdc, 0x80, 0x8f, 0xfc, 0x38, 0xa1, 0x6c, 0x8a, 0x9a, 0xf8, 0x00, 0x2c, 0x37, 0x08, 0x08, 0xbb,
	0xf0, 0x49, 0x8c, 0x5a, 0xf8, 0x08, 0xec, 0x3a, 0x93, 0xf8, 0x34, 0x8c, 0x51, 0x1b, 0x63, 0x38,
	0x3c, 0x77, 0xc7, 0x7e, 0x30, 0xbd, 0xaf, 0xe9, 0x28, 0x2d, 0xa6, 0x9e, 0xbf, 0xd3, 0x67, 0x1f,
	0x03, 0x74, 0x2e, 0xfd, 0xc4, 0x0d, 0x62, 0x64, 0xe2, 0x67, 0x70, 0x10, 0x8d, 0xa6, 0xb1, 0x9e,
	0x44, 0x7e, 0x75, 0xc7, 0xc8, 0x52, 0xb3, 0x03, 0xf7, 0x8c, 0x32, 0x57, 0xc5, 0xf9, 0xd0, 0x4d,
	0x5c, 0x04, 0xbb, 0x0b, 0x45, 0x8c, 0x9e, 0x05, 0x64, 0x8c, 0xec, 0x93, 0x33, 0x40, 0x1f, 0x82,
	0x57, 0x5b, 0x85, 0x94, 0x47, 0xcc, 0xa7, 0xcc, 0x4f, 0xa6, 0x68, 0x0f, 0x9b, 0xd0, 0x1a, 0xf9,
	0x17, 0x23, 0x64, 0xa8, 0xb9, 0x21, 0x65, 0x63, 0x37, 0x40, 0x0d, 0xbc, 0x0f, 0xcd, 0x80, 0x5e,
	0xa1, 0xe6, 0xc9, 0x18, 0xf0, 0xd3, 0x4b, 0x57, 0x47, 0x0d, 0x29, 0x8f, 0x13, 0x37, 0x99, 0xc4,
	0x35, 0x35, 0x3f, 0xf4, 0xe8, 0x38, 0x0a, 0x48, 0x42, 0xea, 0x4e, 0x6e, 0x4d, 0xb0, 0xa1, 0xf8,
	0x32, 0x12, 0x05, 0xae, 0x47, 0x86, 0xa8, 0x79, 0xf2, 0xb7, 0x01, 0xe6, 0xf6, 0x47, 0x8e, 0x11,
	0x74, 0x43, 0xca, 0x43, 0x9a, 0x10, 0x9e, 0x4c, 0x23, 0x82, 0xf6, 0x54, 0xdf, 0x73, 0x1a, 0x04,
	0xf4, 0x8a, 0x4f, 0x22, 0x64, 0xa8, 0xbe, 0xd1, 0x88, 0x86, 0x84, 0x7b, 0x6e, 0xa0, 0xb6, 0xea,
	0xc1, 0x0b, 0x8f, 0x86, 0x89, 0x1f, 0x4e, 0xc8, 0x90, 0x7b, 0x2e, 0x23, 0x7c, 0x48, 0xbd, 0xc9,
	0x98, 0x84, 0x89, 0x86, 0x8c, 0x5a, 0xd8, 0x81, 0x4f, 0x18, 0x39, 0xf7, 0x83, 0xe0, 0x03, 0xa7,
	0xad, 0x76, 0xf2, 0xc3, 0xc4, 0xfd, 0x85, 0xa0, 0x8e, 0x1a, 0x13, 0x31, 0xea, 0x91, 0xe1, 0x84,
	0x11, 0xb4, 0xaf, 0x8a, 0x36, 0xf4, 0xb9, 0x1b, 0x0e, 0xf9, 0x16, 0x38, 0x32, 0xcf, 0xf6, 0x7f,
	0x6b, 0x8b, 0x9b, 0x6a, 0x79, 0x7d, 0xdd, 0xd1, 0x7f, 0x00, 0x3f, 0xfc, 0x17, 0x00, 0x00, 0xff,
	0xff, 0x5f, 0x13, 0xb2, 0xfe, 0xde, 0x05, 0x00, 0x00,
}
