<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: note.proto

namespace Ehr\Note;

/**
 * Protobuf type <code>ehr.note.FragmentTopic</code>
 */
class FragmentTopic
{
    /**
     * Generated from protobuf enum <code>NO_TOPIC = 0;</code>
     */
    const NO_TOPIC = 0;
    /**
     * Generated from protobuf enum <code>SUBJECTIVE = 1;</code>
     */
    const SUBJECTIVE = 1;
    /**
     * Generated from protobuf enum <code>REVIEW_OF_SYSTEMS = 2;</code>
     */
    const REVIEW_OF_SYSTEMS = 2;
    /**
     * Generated from protobuf enum <code>MEDICAL_HISTORY = 3;</code>
     */
    const MEDICAL_HISTORY = 3;
    /**
     * Generated from protobuf enum <code>ALLERGIES = 4;</code>
     */
    const ALLERGIES = 4;
    /**
     * Generated from protobuf enum <code>MEDICATIONS = 5;</code>
     */
    const MEDICATIONS = 5;
    /**
     * Generated from protobuf enum <code>FAMILY_HISTORY = 6;</code>
     */
    const FAMILY_HISTORY = 6;
    /**
     * Generated from protobuf enum <code>SOCIAL_HISTORY = 7;</code>
     */
    const SOCIAL_HISTORY = 7;
    /**
     * Generated from protobuf enum <code>VITALS = 8;</code>
     */
    const VITALS = 8;
    /**
     * Generated from protobuf enum <code>PHYSICAL_EXAM = 9;</code>
     */
    const PHYSICAL_EXAM = 9;
    /**
     * Generated from protobuf enum <code>LABORATORY_DATA = 10;</code>
     */
    const LABORATORY_DATA = 10;
    /**
     * Generated from protobuf enum <code>MEDICAL_PROBLEM = 11;</code>
     */
    const MEDICAL_PROBLEM = 11;
}

