<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: note.proto

namespace Ehr\Note;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ehr.note.NoteFragment</code>
 */
class NoteFragment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_created = 2;</code>
     */
    private $date_created = null;
    /**
     * Generated from protobuf field <code>string note_fragment_guid = 3;</code>
     */
    private $note_fragment_guid = '';
    /**
     * Generated from protobuf field <code>string note_guid = 4;</code>
     */
    private $note_guid = '';
    /**
     * Generated from protobuf field <code>string issue_guid = 5;</code>
     */
    private $issue_guid = '';
    /**
     * recommend using watson api to determine from description
     *
     * Generated from protobuf field <code>string icd_10_code = 6;</code>
     */
    private $icd_10_code = '';
    /**
     * recommend using watson api to determine from description
     *
     * Generated from protobuf field <code>string icd_10_long = 7;</code>
     */
    private $icd_10_long = '';
    /**
     * free text, human readable
     *
     * Generated from protobuf field <code>string description = 8;</code>
     */
    private $description = '';
    /**
     * Generated from protobuf field <code>.ehr.note.NoteFragmentStatus status = 9;</code>
     */
    private $status = 0;
    /**
     * Generated from protobuf field <code>.ehr.note.FragmentPriority priority = 10;</code>
     */
    private $priority = 0;
    /**
     * Generated from protobuf field <code>.ehr.note.FragmentTopic topic = 11;</code>
     */
    private $topic = 0;
    /**
     * Generated from protobuf field <code>string markdown_content = 12;</code>
     */
    private $markdown_content = '';
    /**
     * Generated from protobuf field <code>repeated string tags = 13;</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type \Google\Protobuf\Timestamp $date_created
     *     @type string $note_fragment_guid
     *     @type string $note_guid
     *     @type string $issue_guid
     *     @type string $icd_10_code
     *           recommend using watson api to determine from description
     *     @type string $icd_10_long
     *           recommend using watson api to determine from description
     *     @type string $description
     *           free text, human readable
     *     @type int $status
     *     @type int $priority
     *     @type int $topic
     *     @type string $markdown_content
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $tags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Note::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_created = 2;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getDateCreated()
    {
        return $this->date_created;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_created = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setDateCreated($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->date_created = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string note_fragment_guid = 3;</code>
     * @return string
     */
    public function getNoteFragmentGuid()
    {
        return $this->note_fragment_guid;
    }

    /**
     * Generated from protobuf field <code>string note_fragment_guid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNoteFragmentGuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->note_fragment_guid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string note_guid = 4;</code>
     * @return string
     */
    public function getNoteGuid()
    {
        return $this->note_guid;
    }

    /**
     * Generated from protobuf field <code>string note_guid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNoteGuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->note_guid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string issue_guid = 5;</code>
     * @return string
     */
    public function getIssueGuid()
    {
        return $this->issue_guid;
    }

    /**
     * Generated from protobuf field <code>string issue_guid = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setIssueGuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->issue_guid = $var;

        return $this;
    }

    /**
     * recommend using watson api to determine from description
     *
     * Generated from protobuf field <code>string icd_10_code = 6;</code>
     * @return string
     */
    public function getIcd10Code()
    {
        return $this->icd_10_code;
    }

    /**
     * recommend using watson api to determine from description
     *
     * Generated from protobuf field <code>string icd_10_code = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setIcd10Code($var)
    {
        GPBUtil::checkString($var, True);
        $this->icd_10_code = $var;

        return $this;
    }

    /**
     * recommend using watson api to determine from description
     *
     * Generated from protobuf field <code>string icd_10_long = 7;</code>
     * @return string
     */
    public function getIcd10Long()
    {
        return $this->icd_10_long;
    }

    /**
     * recommend using watson api to determine from description
     *
     * Generated from protobuf field <code>string icd_10_long = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setIcd10Long($var)
    {
        GPBUtil::checkString($var, True);
        $this->icd_10_long = $var;

        return $this;
    }

    /**
     * free text, human readable
     *
     * Generated from protobuf field <code>string description = 8;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * free text, human readable
     *
     * Generated from protobuf field <code>string description = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ehr.note.NoteFragmentStatus status = 9;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.ehr.note.NoteFragmentStatus status = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Ehr\Note\NoteFragmentStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ehr.note.FragmentPriority priority = 10;</code>
     * @return int
     */
    public function getPriority()
    {
        return $this->priority;
    }

    /**
     * Generated from protobuf field <code>.ehr.note.FragmentPriority priority = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setPriority($var)
    {
        GPBUtil::checkEnum($var, \Ehr\Note\FragmentPriority::class);
        $this->priority = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ehr.note.FragmentTopic topic = 11;</code>
     * @return int
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * Generated from protobuf field <code>.ehr.note.FragmentTopic topic = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkEnum($var, \Ehr\Note\FragmentTopic::class);
        $this->topic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string markdown_content = 12;</code>
     * @return string
     */
    public function getMarkdownContent()
    {
        return $this->markdown_content;
    }

    /**
     * Generated from protobuf field <code>string markdown_content = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setMarkdownContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->markdown_content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string tags = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>repeated string tags = 13;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

}

