<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: note.proto

namespace Ehr\Note;

/**
 * Protobuf type <code>ehr.note.NoteType</code>
 */
class NoteType
{
    /**
     * Generated from protobuf enum <code>NO_NOTE_TYPE = 0;</code>
     */
    const NO_NOTE_TYPE = 0;
    /**
     * Generated from protobuf enum <code>FOLLOW_UP = 1;</code>
     */
    const FOLLOW_UP = 1;
    /**
     * Generated from protobuf enum <code>PHONE_CALL = 2;</code>
     */
    const PHONE_CALL = 2;
    /**
     * Generated from protobuf enum <code>CONTINUED_CARE_DOCUMENTATION = 4;</code>
     */
    const CONTINUED_CARE_DOCUMENTATION = 4;
    /**
     * Generated from protobuf enum <code>REFILL_DOCUMENTATION = 5;</code>
     */
    const REFILL_DOCUMENTATION = 5;
    /**
     * Generated from protobuf enum <code>INTAKE = 6;</code>
     */
    const INTAKE = 6;
    /**
     * Generated from protobuf enum <code>PROCEDURE = 7;</code>
     */
    const PROCEDURE = 7;
    /**
     * Generated from protobuf enum <code>HISTORY_AND_PHYSICAL = 8;</code>
     */
    const HISTORY_AND_PHYSICAL = 8;
}

