<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: note.proto

namespace Ehr\Note;

/**
 * Protobuf type <code>ehr.note.RecordPriority</code>
 */
class RecordPriority
{
    /**
     * Generated from protobuf enum <code>NO_PRIORITY = 0;</code>
     */
    const NO_PRIORITY = 0;
    /**
     * Generated from protobuf enum <code>HIGH = 1;</code>
     */
    const HIGH = 1;
    /**
     * Generated from protobuf enum <code>NORMAL = 2;</code>
     */
    const NORMAL = 2;
    /**
     * Generated from protobuf enum <code>LOW = 3;</code>
     */
    const LOW = 3;
}

