# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: noteservice.proto

require 'google/protobuf'

require 'note_pb'
require 'http_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ehr.noteservice.NoteServiceResponseStatus" do
    optional :http_code, :enum, 1, "ehr.http.StatusCodes"
    optional :message, :string, 2
  end
  add_message "ehr.noteservice.CreateNoteRequest" do
    optional :note, :message, 1, "ehr.note.Note"
  end
  add_message "ehr.noteservice.CreateNoteResponse" do
    optional :status, :message, 1, "ehr.noteservice.NoteServiceResponseStatus"
    optional :note, :message, 2, "ehr.note.Note"
  end
  add_message "ehr.noteservice.DeleteNoteRequest" do
    optional :id, :int64, 1
  end
  add_message "ehr.noteservice.DeleteNoteResponse" do
    optional :status, :message, 1, "ehr.noteservice.NoteServiceResponseStatus"
  end
  add_message "ehr.noteservice.RetrieveNoteRequest" do
    optional :id, :int64, 1
  end
  add_message "ehr.noteservice.RetrieveNoteResponse" do
    optional :status, :message, 1, "ehr.noteservice.NoteServiceResponseStatus"
    optional :note, :message, 2, "ehr.note.Note"
  end
  add_message "ehr.noteservice.FindNoteRequest" do
    optional :search_terms, :string, 1
    optional :author_guid, :string, 2
    optional :patient_guid, :string, 3
    optional :visit_guid, :string, 4
  end
  add_message "ehr.noteservice.FindNoteResponse" do
    optional :status, :message, 1, "ehr.noteservice.NoteServiceResponseStatus"
    repeated :note, :message, 2, "ehr.note.Note"
  end
  add_message "ehr.noteservice.UpdateNoteRequest" do
    optional :id, :int64, 1
    optional :note, :message, 2, "ehr.note.Note"
  end
  add_message "ehr.noteservice.UpdateNoteResponse" do
    optional :status, :message, 1, "ehr.noteservice.NoteServiceResponseStatus"
  end
end

module Ehr
  module Noteservice
    NoteServiceResponseStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("ehr.noteservice.NoteServiceResponseStatus").msgclass
    CreateNoteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ehr.noteservice.CreateNoteRequest").msgclass
    CreateNoteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ehr.noteservice.CreateNoteResponse").msgclass
    DeleteNoteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ehr.noteservice.DeleteNoteRequest").msgclass
    DeleteNoteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ehr.noteservice.DeleteNoteResponse").msgclass
    RetrieveNoteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ehr.noteservice.RetrieveNoteRequest").msgclass
    RetrieveNoteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ehr.noteservice.RetrieveNoteResponse").msgclass
    FindNoteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ehr.noteservice.FindNoteRequest").msgclass
    FindNoteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ehr.noteservice.FindNoteResponse").msgclass
    UpdateNoteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ehr.noteservice.UpdateNoteRequest").msgclass
    UpdateNoteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ehr.noteservice.UpdateNoteResponse").msgclass
  end
end
