# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: httpstatuscodes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='httpstatuscodes.proto',
  package='ehr.httpstatuscodes',
  syntax='proto3',
  serialized_options=_b('Z\005ehrpb'),
  serialized_pb=_b('\n\x15httpstatuscodes.proto\x12\x13\x65hr.httpstatuscodes*\x8f\x01\n\x0eHttpStatusCode\x12\x06\n\x02OK\x10\x00\x12\x10\n\x0cNOT_MODIFIED\x10\x01\x12\x12\n\x0eNOT_AUTHORIZED\x10\x03\x12\r\n\tNOT_FOUND\x10\x04\x12\x0c\n\x08\x43ONFLICT\x10\x05\x12\x19\n\x15INTERNAL_SERVER_ERROR\x10\x06\x12\x17\n\x13SERVICE_UNAVAILABLE\x10\x07\x42\x07Z\x05\x65hrpbb\x06proto3')
)

_HTTPSTATUSCODE = _descriptor.EnumDescriptor(
  name='HttpStatusCode',
  full_name='ehr.httpstatuscodes.HttpStatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_MODIFIED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_AUTHORIZED', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_FOUND', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONFLICT', index=4, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_SERVER_ERROR', index=5, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVICE_UNAVAILABLE', index=6, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=47,
  serialized_end=190,
)
_sym_db.RegisterEnumDescriptor(_HTTPSTATUSCODE)

HttpStatusCode = enum_type_wrapper.EnumTypeWrapper(_HTTPSTATUSCODE)
OK = 0
NOT_MODIFIED = 1
NOT_AUTHORIZED = 3
NOT_FOUND = 4
CONFLICT = 5
INTERNAL_SERVER_ERROR = 6
SERVICE_UNAVAILABLE = 7


DESCRIPTOR.enum_types_by_name['HttpStatusCode'] = _HTTPSTATUSCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
