<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: noteservice.proto

namespace Ehr\Noteservice;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ehr.noteservice.CreateNoteResponse</code>
 */
class CreateNoteResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ehr.noteservice.NoteServiceResponseStatus status = 1;</code>
     */
    private $status = null;
    /**
     * Generated from protobuf field <code>.ehr.note.Note note = 2;</code>
     */
    private $note = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ehr\Noteservice\NoteServiceResponseStatus $status
     *     @type \Ehr\Note\Note $note
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Noteservice::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ehr.noteservice.NoteServiceResponseStatus status = 1;</code>
     * @return \Ehr\Noteservice\NoteServiceResponseStatus
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.ehr.noteservice.NoteServiceResponseStatus status = 1;</code>
     * @param \Ehr\Noteservice\NoteServiceResponseStatus $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Ehr\Noteservice\NoteServiceResponseStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ehr.note.Note note = 2;</code>
     * @return \Ehr\Note\Note
     */
    public function getNote()
    {
        return $this->note;
    }

    /**
     * Generated from protobuf field <code>.ehr.note.Note note = 2;</code>
     * @param \Ehr\Note\Note $var
     * @return $this
     */
    public function setNote($var)
    {
        GPBUtil::checkMessage($var, \Ehr\Note\Note::class);
        $this->note = $var;

        return $this;
    }

}

