// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: http.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import <stdatomic.h>

#import "HTTP.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - HTTPRoot

@implementation HTTPRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - Enum StatusCodes

GPBEnumDescriptor *StatusCodes_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "Ok\000NotModified\000NotAuthorized\000NotFound\000Co"
        "nflict\000InternalServerError\000ServiceUnavai"
        "lable\000";
    static const int32_t values[] = {
        StatusCodes_Ok,
        StatusCodes_NotModified,
        StatusCodes_NotAuthorized,
        StatusCodes_NotFound,
        StatusCodes_Conflict,
        StatusCodes_InternalServerError,
        StatusCodes_ServiceUnavailable,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(StatusCodes)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:StatusCodes_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL StatusCodes_IsValidValue(int32_t value__) {
  switch (value__) {
    case StatusCodes_Ok:
    case StatusCodes_NotModified:
    case StatusCodes_NotAuthorized:
    case StatusCodes_NotFound:
    case StatusCodes_Conflict:
    case StatusCodes_InternalServerError:
    case StatusCodes_ServiceUnavailable:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
