// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: http.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum StatusCodes

/** Sticking to only HTTP status codes that can be mapped to a gRPC code. */
typedef GPB_ENUM(StatusCodes) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  StatusCodes_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** OK | 200 */
  StatusCodes_Ok = 0,

  /** CANCELLED | 304 */
  StatusCodes_NotModified = 1,

  /** PERMISSION_DENIED or UNAUTHENTICATED | 401 */
  StatusCodes_NotAuthorized = 3,

  /** NOT_FOUND | 404 */
  StatusCodes_NotFound = 4,

  /** ALREADY_EXISTS | 409 */
  StatusCodes_Conflict = 5,

  /** INTERNAL | 500 */
  StatusCodes_InternalServerError = 6,

  /** UNAVAILABLE | 503 */
  StatusCodes_ServiceUnavailable = 7,
};

GPBEnumDescriptor *StatusCodes_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL StatusCodes_IsValidValue(int32_t value);

#pragma mark - HTTPRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface HTTPRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
